// Generated by jextract

package com.twitter.teruteru128.preview.opencl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$103() {}
    static final VarHandle const$0 = constants$82.const$1.varHandle(MemoryLayout.PathElement.groupElement("$anon$2"), MemoryLayout.PathElement.groupElement("hi"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        MemoryLayout.sequenceLayout(4, JAVA_SHORT).withName("s"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("x"),
            JAVA_SHORT.withName("y"),
            JAVA_SHORT.withName("z"),
            JAVA_SHORT.withName("w")
        ).withName("$anon$0"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("s0"),
            JAVA_SHORT.withName("s1"),
            JAVA_SHORT.withName("s2"),
            JAVA_SHORT.withName("s3")
        ).withName("$anon$1"),
        MemoryLayout.structLayout(
            MemoryLayout.unionLayout(
                MemoryLayout.sequenceLayout(2, JAVA_SHORT).withName("s"),
                MemoryLayout.structLayout(
                    JAVA_SHORT.withName("x"),
                    JAVA_SHORT.withName("y")
                ).withName("$anon$0"),
                MemoryLayout.structLayout(
                    JAVA_SHORT.withName("s0"),
                    JAVA_SHORT.withName("s1")
                ).withName("$anon$1"),
                MemoryLayout.structLayout(
                    JAVA_SHORT.withName("lo"),
                    JAVA_SHORT.withName("hi")
                ).withName("$anon$2")
            ).withName("lo"),
            MemoryLayout.unionLayout(
                MemoryLayout.sequenceLayout(2, JAVA_SHORT).withName("s"),
                MemoryLayout.structLayout(
                    JAVA_SHORT.withName("x"),
                    JAVA_SHORT.withName("y")
                ).withName("$anon$0"),
                MemoryLayout.structLayout(
                    JAVA_SHORT.withName("s0"),
                    JAVA_SHORT.withName("s1")
                ).withName("$anon$1"),
                MemoryLayout.structLayout(
                    JAVA_SHORT.withName("lo"),
                    JAVA_SHORT.withName("hi")
                ).withName("$anon$2")
            ).withName("hi")
        ).withName("$anon$2")
    ).withName("");
    static final VarHandle const$2 = constants$103.const$1.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$3 = constants$103.const$1.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$4 = constants$103.const$1.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("z"));
    static final VarHandle const$5 = constants$103.const$1.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("w"));
}


