// Generated by jextract

package com.twitter.teruteru128.preview.opencl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_SHORT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "_wctomb_s_l",
        constants$53.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "wcstombs_s",
        constants$50.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "wcstombs",
        constants$51.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_wcstombs_s_l",
        constants$51.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "_wcstombs_l",
        constants$51.const$4
    );
}


