// Generated by jextract

package com.twitter.teruteru128.preview.opencl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$250 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$250() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(clEnqueueMemAdviseINTEL_fn.class, "apply", constants$250.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$250.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "clHostMemAllocINTEL",
        constants$247.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "clDeviceMemAllocINTEL",
        constants$248.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "clSharedMemAllocINTEL",
        constants$248.const$2
    );
}


