// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _CERT_POLICY_CONSTRAINTS_INFO {
 *     BOOL fRequireExplicitPolicy;
 *     DWORD dwRequireExplicitPolicySkipCerts;
 *     BOOL fInhibitPolicyMapping;
 *     DWORD dwInhibitPolicyMappingSkipCerts;
 * };
 * }
 */
public class _CERT_POLICY_CONSTRAINTS_INFO {

    public static MemoryLayout $LAYOUT() {
        return constants$2035.const$0;
    }
    public static VarHandle fRequireExplicitPolicy$VH() {
        return constants$2035.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BOOL fRequireExplicitPolicy;
     * }
     */
    public static int fRequireExplicitPolicy$get(MemorySegment seg) {
        return (int)constants$2035.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BOOL fRequireExplicitPolicy;
     * }
     */
    public static void fRequireExplicitPolicy$set(MemorySegment seg, int x) {
        constants$2035.const$1.set(seg, x);
    }
    public static int fRequireExplicitPolicy$get(MemorySegment seg, long index) {
        return (int)constants$2035.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void fRequireExplicitPolicy$set(MemorySegment seg, long index, int x) {
        constants$2035.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dwRequireExplicitPolicySkipCerts$VH() {
        return constants$2035.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD dwRequireExplicitPolicySkipCerts;
     * }
     */
    public static int dwRequireExplicitPolicySkipCerts$get(MemorySegment seg) {
        return (int)constants$2035.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD dwRequireExplicitPolicySkipCerts;
     * }
     */
    public static void dwRequireExplicitPolicySkipCerts$set(MemorySegment seg, int x) {
        constants$2035.const$2.set(seg, x);
    }
    public static int dwRequireExplicitPolicySkipCerts$get(MemorySegment seg, long index) {
        return (int)constants$2035.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void dwRequireExplicitPolicySkipCerts$set(MemorySegment seg, long index, int x) {
        constants$2035.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle fInhibitPolicyMapping$VH() {
        return constants$2035.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BOOL fInhibitPolicyMapping;
     * }
     */
    public static int fInhibitPolicyMapping$get(MemorySegment seg) {
        return (int)constants$2035.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BOOL fInhibitPolicyMapping;
     * }
     */
    public static void fInhibitPolicyMapping$set(MemorySegment seg, int x) {
        constants$2035.const$3.set(seg, x);
    }
    public static int fInhibitPolicyMapping$get(MemorySegment seg, long index) {
        return (int)constants$2035.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void fInhibitPolicyMapping$set(MemorySegment seg, long index, int x) {
        constants$2035.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dwInhibitPolicyMappingSkipCerts$VH() {
        return constants$2035.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD dwInhibitPolicyMappingSkipCerts;
     * }
     */
    public static int dwInhibitPolicyMappingSkipCerts$get(MemorySegment seg) {
        return (int)constants$2035.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD dwInhibitPolicyMappingSkipCerts;
     * }
     */
    public static void dwInhibitPolicyMappingSkipCerts$set(MemorySegment seg, int x) {
        constants$2035.const$4.set(seg, x);
    }
    public static int dwInhibitPolicyMappingSkipCerts$get(MemorySegment seg, long index) {
        return (int)constants$2035.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void dwInhibitPolicyMappingSkipCerts$set(MemorySegment seg, long index, int x) {
        constants$2035.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


