// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _CERT_TPM_SPECIFICATION_INFO {
 *     LPWSTR pwszFamily;
 *     DWORD dwLevel;
 *     DWORD dwRevision;
 * };
 * }
 */
public class _CERT_TPM_SPECIFICATION_INFO {

    public static MemoryLayout $LAYOUT() {
        return constants$2071.const$1;
    }
    public static VarHandle pwszFamily$VH() {
        return constants$2071.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LPWSTR pwszFamily;
     * }
     */
    public static MemorySegment pwszFamily$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$2071.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LPWSTR pwszFamily;
     * }
     */
    public static void pwszFamily$set(MemorySegment seg, MemorySegment x) {
        constants$2071.const$2.set(seg, x);
    }
    public static MemorySegment pwszFamily$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$2071.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void pwszFamily$set(MemorySegment seg, long index, MemorySegment x) {
        constants$2071.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dwLevel$VH() {
        return constants$2071.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD dwLevel;
     * }
     */
    public static int dwLevel$get(MemorySegment seg) {
        return (int)constants$2071.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD dwLevel;
     * }
     */
    public static void dwLevel$set(MemorySegment seg, int x) {
        constants$2071.const$3.set(seg, x);
    }
    public static int dwLevel$get(MemorySegment seg, long index) {
        return (int)constants$2071.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void dwLevel$set(MemorySegment seg, long index, int x) {
        constants$2071.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dwRevision$VH() {
        return constants$2071.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD dwRevision;
     * }
     */
    public static int dwRevision$get(MemorySegment seg) {
        return (int)constants$2071.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD dwRevision;
     * }
     */
    public static void dwRevision$set(MemorySegment seg, int x) {
        constants$2071.const$4.set(seg, x);
    }
    public static int dwRevision$get(MemorySegment seg, long index) {
        return (int)constants$2071.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void dwRevision$set(MemorySegment seg, long index, int x) {
        constants$2071.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


