// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*_CoreCrtNonSecureSearchSortCompareFunction)(void*,void*);
 * }
 */
public interface _CoreCrtNonSecureSearchSortCompareFunction {

    int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1);
    static MemorySegment allocate(_CoreCrtNonSecureSearchSortCompareFunction fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$2955.const$1, fi, constants$34.const$0, scope);
    }
    static _CoreCrtNonSecureSearchSortCompareFunction ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1) -> {
            try {
                return (int)constants$92.const$2.invokeExact(symbol, __x0, __x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


