// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _CRYPT_PROPERTY_REF {
 *     PWSTR pszProperty;
 *     ULONG cbValue;
 *     PUCHAR pbValue;
 * };
 * }
 */
public class _CRYPT_PROPERTY_REF {

    public static MemoryLayout $LAYOUT() {
        return constants$1970.const$4;
    }
    public static VarHandle pszProperty$VH() {
        return constants$1970.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PWSTR pszProperty;
     * }
     */
    public static MemorySegment pszProperty$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$1970.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PWSTR pszProperty;
     * }
     */
    public static void pszProperty$set(MemorySegment seg, MemorySegment x) {
        constants$1970.const$5.set(seg, x);
    }
    public static MemorySegment pszProperty$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$1970.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void pszProperty$set(MemorySegment seg, long index, MemorySegment x) {
        constants$1970.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle cbValue$VH() {
        return constants$1971.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * ULONG cbValue;
     * }
     */
    public static int cbValue$get(MemorySegment seg) {
        return (int)constants$1971.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * ULONG cbValue;
     * }
     */
    public static void cbValue$set(MemorySegment seg, int x) {
        constants$1971.const$0.set(seg, x);
    }
    public static int cbValue$get(MemorySegment seg, long index) {
        return (int)constants$1971.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void cbValue$set(MemorySegment seg, long index, int x) {
        constants$1971.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pbValue$VH() {
        return constants$1971.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PUCHAR pbValue;
     * }
     */
    public static MemorySegment pbValue$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$1971.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PUCHAR pbValue;
     * }
     */
    public static void pbValue$set(MemorySegment seg, MemorySegment x) {
        constants$1971.const$1.set(seg, x);
    }
    public static MemorySegment pbValue$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$1971.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void pbValue$set(MemorySegment seg, long index, MemorySegment x) {
        constants$1971.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


