// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION {
 *     DWORD64 IoReadBytesLimit;
 *     DWORD64 IoWriteBytesLimit;
 *     LARGE_INTEGER PerJobUserTimeLimit;
 *     DWORD64 JobMemoryLimit;
 *     JOBOBJECT_RATE_CONTROL_TOLERANCE RateControlTolerance;
 *     JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL RateControlToleranceInterval;
 *     DWORD LimitFlags;
 * };
 * }
 */
public class _JOBOBJECT_NOTIFICATION_LIMIT_INFORMATION {

    public static MemoryLayout $LAYOUT() {
        return constants$208.const$2;
    }
    public static VarHandle IoReadBytesLimit$VH() {
        return constants$208.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD64 IoReadBytesLimit;
     * }
     */
    public static long IoReadBytesLimit$get(MemorySegment seg) {
        return (long)constants$208.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD64 IoReadBytesLimit;
     * }
     */
    public static void IoReadBytesLimit$set(MemorySegment seg, long x) {
        constants$208.const$3.set(seg, x);
    }
    public static long IoReadBytesLimit$get(MemorySegment seg, long index) {
        return (long)constants$208.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void IoReadBytesLimit$set(MemorySegment seg, long index, long x) {
        constants$208.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle IoWriteBytesLimit$VH() {
        return constants$208.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD64 IoWriteBytesLimit;
     * }
     */
    public static long IoWriteBytesLimit$get(MemorySegment seg) {
        return (long)constants$208.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD64 IoWriteBytesLimit;
     * }
     */
    public static void IoWriteBytesLimit$set(MemorySegment seg, long x) {
        constants$208.const$4.set(seg, x);
    }
    public static long IoWriteBytesLimit$get(MemorySegment seg, long index) {
        return (long)constants$208.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void IoWriteBytesLimit$set(MemorySegment seg, long index, long x) {
        constants$208.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment PerJobUserTimeLimit$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static VarHandle JobMemoryLimit$VH() {
        return constants$208.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD64 JobMemoryLimit;
     * }
     */
    public static long JobMemoryLimit$get(MemorySegment seg) {
        return (long)constants$208.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD64 JobMemoryLimit;
     * }
     */
    public static void JobMemoryLimit$set(MemorySegment seg, long x) {
        constants$208.const$5.set(seg, x);
    }
    public static long JobMemoryLimit$get(MemorySegment seg, long index) {
        return (long)constants$208.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void JobMemoryLimit$set(MemorySegment seg, long index, long x) {
        constants$208.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle RateControlTolerance$VH() {
        return constants$209.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * JOBOBJECT_RATE_CONTROL_TOLERANCE RateControlTolerance;
     * }
     */
    public static int RateControlTolerance$get(MemorySegment seg) {
        return (int)constants$209.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * JOBOBJECT_RATE_CONTROL_TOLERANCE RateControlTolerance;
     * }
     */
    public static void RateControlTolerance$set(MemorySegment seg, int x) {
        constants$209.const$0.set(seg, x);
    }
    public static int RateControlTolerance$get(MemorySegment seg, long index) {
        return (int)constants$209.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void RateControlTolerance$set(MemorySegment seg, long index, int x) {
        constants$209.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle RateControlToleranceInterval$VH() {
        return constants$209.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL RateControlToleranceInterval;
     * }
     */
    public static int RateControlToleranceInterval$get(MemorySegment seg) {
        return (int)constants$209.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * JOBOBJECT_RATE_CONTROL_TOLERANCE_INTERVAL RateControlToleranceInterval;
     * }
     */
    public static void RateControlToleranceInterval$set(MemorySegment seg, int x) {
        constants$209.const$1.set(seg, x);
    }
    public static int RateControlToleranceInterval$get(MemorySegment seg, long index) {
        return (int)constants$209.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void RateControlToleranceInterval$set(MemorySegment seg, long index, int x) {
        constants$209.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle LimitFlags$VH() {
        return constants$209.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD LimitFlags;
     * }
     */
    public static int LimitFlags$get(MemorySegment seg) {
        return (int)constants$209.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD LimitFlags;
     * }
     */
    public static void LimitFlags$set(MemorySegment seg, int x) {
        constants$209.const$2.set(seg, x);
    }
    public static int LimitFlags$get(MemorySegment seg, long index) {
        return (int)constants$209.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void LimitFlags$set(MemorySegment seg, long index, int x) {
        constants$209.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


