// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _JOBOBJECT_ASSOCIATE_COMPLETION_PORT {
 *     PVOID CompletionKey;
 *     HANDLE CompletionPort;
 * };
 * }
 */
public class _JOBOBJECT_ASSOCIATE_COMPLETION_PORT {

    public static MemoryLayout $LAYOUT() {
        return constants$207.const$2;
    }
    public static VarHandle CompletionKey$VH() {
        return constants$207.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PVOID CompletionKey;
     * }
     */
    public static MemorySegment CompletionKey$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$207.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PVOID CompletionKey;
     * }
     */
    public static void CompletionKey$set(MemorySegment seg, MemorySegment x) {
        constants$207.const$3.set(seg, x);
    }
    public static MemorySegment CompletionKey$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$207.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void CompletionKey$set(MemorySegment seg, long index, MemorySegment x) {
        constants$207.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle CompletionPort$VH() {
        return constants$207.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * HANDLE CompletionPort;
     * }
     */
    public static MemorySegment CompletionPort$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$207.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * HANDLE CompletionPort;
     * }
     */
    public static void CompletionPort$set(MemorySegment seg, MemorySegment x) {
        constants$207.const$4.set(seg, x);
    }
    public static MemorySegment CompletionPort$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$207.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void CompletionPort$set(MemorySegment seg, long index, MemorySegment x) {
        constants$207.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


