// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _KEY_EVENT_RECORD {
 *     BOOL bKeyDown;
 *     WORD wRepeatCount;
 *     WORD wVirtualKeyCode;
 *     WORD wVirtualScanCode;
 *     union  uChar;
 *     DWORD dwControlKeyState;
 * };
 * }
 */
public class _KEY_EVENT_RECORD {

    public static MemoryLayout $LAYOUT() {
        return constants$1449.const$0;
    }
    public static VarHandle bKeyDown$VH() {
        return constants$1449.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BOOL bKeyDown;
     * }
     */
    public static int bKeyDown$get(MemorySegment seg) {
        return (int)constants$1449.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BOOL bKeyDown;
     * }
     */
    public static void bKeyDown$set(MemorySegment seg, int x) {
        constants$1449.const$1.set(seg, x);
    }
    public static int bKeyDown$get(MemorySegment seg, long index) {
        return (int)constants$1449.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void bKeyDown$set(MemorySegment seg, long index, int x) {
        constants$1449.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle wRepeatCount$VH() {
        return constants$1449.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * WORD wRepeatCount;
     * }
     */
    public static short wRepeatCount$get(MemorySegment seg) {
        return (short)constants$1449.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * WORD wRepeatCount;
     * }
     */
    public static void wRepeatCount$set(MemorySegment seg, short x) {
        constants$1449.const$2.set(seg, x);
    }
    public static short wRepeatCount$get(MemorySegment seg, long index) {
        return (short)constants$1449.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void wRepeatCount$set(MemorySegment seg, long index, short x) {
        constants$1449.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle wVirtualKeyCode$VH() {
        return constants$1449.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * WORD wVirtualKeyCode;
     * }
     */
    public static short wVirtualKeyCode$get(MemorySegment seg) {
        return (short)constants$1449.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * WORD wVirtualKeyCode;
     * }
     */
    public static void wVirtualKeyCode$set(MemorySegment seg, short x) {
        constants$1449.const$3.set(seg, x);
    }
    public static short wVirtualKeyCode$get(MemorySegment seg, long index) {
        return (short)constants$1449.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void wVirtualKeyCode$set(MemorySegment seg, long index, short x) {
        constants$1449.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle wVirtualScanCode$VH() {
        return constants$1449.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * WORD wVirtualScanCode;
     * }
     */
    public static short wVirtualScanCode$get(MemorySegment seg) {
        return (short)constants$1449.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * WORD wVirtualScanCode;
     * }
     */
    public static void wVirtualScanCode$set(MemorySegment seg, short x) {
        constants$1449.const$4.set(seg, x);
    }
    public static short wVirtualScanCode$get(MemorySegment seg, long index) {
        return (short)constants$1449.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void wVirtualScanCode$set(MemorySegment seg, long index, short x) {
        constants$1449.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
     * union {
     *     WCHAR UnicodeChar;
     *     CHAR AsciiChar;
     * };
     * }
     */
    public static final class uChar {

        // Suppresses default constructor, ensuring non-instantiability.
        private uChar() {}
        public static MemoryLayout $LAYOUT() {
            return constants$1449.const$5;
        }
        public static VarHandle UnicodeChar$VH() {
            return constants$1450.const$0;
        }
        /**
         * Getter for field:
         * {@snippet :
         * WCHAR UnicodeChar;
         * }
         */
        public static short UnicodeChar$get(MemorySegment seg) {
            return (short)constants$1450.const$0.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * WCHAR UnicodeChar;
         * }
         */
        public static void UnicodeChar$set(MemorySegment seg, short x) {
            constants$1450.const$0.set(seg, x);
        }
        public static short UnicodeChar$get(MemorySegment seg, long index) {
            return (short)constants$1450.const$0.get(seg.asSlice(index*sizeof()));
        }
        public static void UnicodeChar$set(MemorySegment seg, long index, short x) {
            constants$1450.const$0.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle AsciiChar$VH() {
            return constants$1450.const$1;
        }
        /**
         * Getter for field:
         * {@snippet :
         * CHAR AsciiChar;
         * }
         */
        public static byte AsciiChar$get(MemorySegment seg) {
            return (byte)constants$1450.const$1.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * CHAR AsciiChar;
         * }
         */
        public static void AsciiChar$set(MemorySegment seg, byte x) {
            constants$1450.const$1.set(seg, x);
        }
        public static byte AsciiChar$get(MemorySegment seg, long index) {
            return (byte)constants$1450.const$1.get(seg.asSlice(index*sizeof()));
        }
        public static void AsciiChar$set(MemorySegment seg, long index, byte x) {
            constants$1450.const$1.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment uChar$slice(MemorySegment seg) {
        return seg.asSlice(10, 2);
    }
    public static VarHandle dwControlKeyState$VH() {
        return constants$1450.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD dwControlKeyState;
     * }
     */
    public static int dwControlKeyState$get(MemorySegment seg) {
        return (int)constants$1450.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD dwControlKeyState;
     * }
     */
    public static void dwControlKeyState$set(MemorySegment seg, int x) {
        constants$1450.const$2.set(seg, x);
    }
    public static int dwControlKeyState$get(MemorySegment seg, long index) {
        return (int)constants$1450.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void dwControlKeyState$set(MemorySegment seg, long index, int x) {
        constants$1450.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


