// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _STORAGE_PHYSICAL_TOPOLOGY_DESCRIPTOR {
 *     DWORD Version;
 *     DWORD Size;
 *     DWORD NodeCount;
 *     DWORD Reserved;
 *     STORAGE_PHYSICAL_NODE_DATA Node[1];
 * };
 * }
 */
public class _STORAGE_PHYSICAL_TOPOLOGY_DESCRIPTOR {

    public static MemoryLayout $LAYOUT() {
        return constants$2424.const$2;
    }
    public static VarHandle Version$VH() {
        return constants$2424.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD Version;
     * }
     */
    public static int Version$get(MemorySegment seg) {
        return (int)constants$2424.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD Version;
     * }
     */
    public static void Version$set(MemorySegment seg, int x) {
        constants$2424.const$3.set(seg, x);
    }
    public static int Version$get(MemorySegment seg, long index) {
        return (int)constants$2424.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void Version$set(MemorySegment seg, long index, int x) {
        constants$2424.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle Size$VH() {
        return constants$2424.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD Size;
     * }
     */
    public static int Size$get(MemorySegment seg) {
        return (int)constants$2424.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD Size;
     * }
     */
    public static void Size$set(MemorySegment seg, int x) {
        constants$2424.const$4.set(seg, x);
    }
    public static int Size$get(MemorySegment seg, long index) {
        return (int)constants$2424.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void Size$set(MemorySegment seg, long index, int x) {
        constants$2424.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle NodeCount$VH() {
        return constants$2424.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD NodeCount;
     * }
     */
    public static int NodeCount$get(MemorySegment seg) {
        return (int)constants$2424.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD NodeCount;
     * }
     */
    public static void NodeCount$set(MemorySegment seg, int x) {
        constants$2424.const$5.set(seg, x);
    }
    public static int NodeCount$get(MemorySegment seg, long index) {
        return (int)constants$2424.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void NodeCount$set(MemorySegment seg, long index, int x) {
        constants$2424.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle Reserved$VH() {
        return constants$2425.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD Reserved;
     * }
     */
    public static int Reserved$get(MemorySegment seg) {
        return (int)constants$2425.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD Reserved;
     * }
     */
    public static void Reserved$set(MemorySegment seg, int x) {
        constants$2425.const$0.set(seg, x);
    }
    public static int Reserved$get(MemorySegment seg, long index) {
        return (int)constants$2425.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void Reserved$set(MemorySegment seg, long index, int x) {
        constants$2425.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment Node$slice(MemorySegment seg) {
        return seg.asSlice(16, 40);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


