// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _TAPE_SET_DRIVE_PARAMETERS {
 *     BOOLEAN ECC;
 *     BOOLEAN Compression;
 *     BOOLEAN DataPadding;
 *     BOOLEAN ReportSetmarks;
 *     DWORD EOTWarningZoneSize;
 * };
 * }
 */
public class _TAPE_SET_DRIVE_PARAMETERS {

    public static MemoryLayout $LAYOUT() {
        return constants$518.const$1;
    }
    public static VarHandle ECC$VH() {
        return constants$518.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BOOLEAN ECC;
     * }
     */
    public static byte ECC$get(MemorySegment seg) {
        return (byte)constants$518.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BOOLEAN ECC;
     * }
     */
    public static void ECC$set(MemorySegment seg, byte x) {
        constants$518.const$2.set(seg, x);
    }
    public static byte ECC$get(MemorySegment seg, long index) {
        return (byte)constants$518.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void ECC$set(MemorySegment seg, long index, byte x) {
        constants$518.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle Compression$VH() {
        return constants$518.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BOOLEAN Compression;
     * }
     */
    public static byte Compression$get(MemorySegment seg) {
        return (byte)constants$518.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BOOLEAN Compression;
     * }
     */
    public static void Compression$set(MemorySegment seg, byte x) {
        constants$518.const$3.set(seg, x);
    }
    public static byte Compression$get(MemorySegment seg, long index) {
        return (byte)constants$518.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void Compression$set(MemorySegment seg, long index, byte x) {
        constants$518.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle DataPadding$VH() {
        return constants$518.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BOOLEAN DataPadding;
     * }
     */
    public static byte DataPadding$get(MemorySegment seg) {
        return (byte)constants$518.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BOOLEAN DataPadding;
     * }
     */
    public static void DataPadding$set(MemorySegment seg, byte x) {
        constants$518.const$4.set(seg, x);
    }
    public static byte DataPadding$get(MemorySegment seg, long index) {
        return (byte)constants$518.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void DataPadding$set(MemorySegment seg, long index, byte x) {
        constants$518.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ReportSetmarks$VH() {
        return constants$518.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BOOLEAN ReportSetmarks;
     * }
     */
    public static byte ReportSetmarks$get(MemorySegment seg) {
        return (byte)constants$518.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BOOLEAN ReportSetmarks;
     * }
     */
    public static void ReportSetmarks$set(MemorySegment seg, byte x) {
        constants$518.const$5.set(seg, x);
    }
    public static byte ReportSetmarks$get(MemorySegment seg, long index) {
        return (byte)constants$518.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void ReportSetmarks$set(MemorySegment seg, long index, byte x) {
        constants$518.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle EOTWarningZoneSize$VH() {
        return constants$519.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD EOTWarningZoneSize;
     * }
     */
    public static int EOTWarningZoneSize$get(MemorySegment seg) {
        return (int)constants$519.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD EOTWarningZoneSize;
     * }
     */
    public static void EOTWarningZoneSize$set(MemorySegment seg, int x) {
        constants$519.const$0.set(seg, x);
    }
    public static int EOTWarningZoneSize$get(MemorySegment seg, long index) {
        return (int)constants$519.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void EOTWarningZoneSize$set(MemorySegment seg, long index, int x) {
        constants$519.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


