// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*APC_CALLBACK_FUNCTION)(unsigned long,void*,void*);
 * }
 */
public interface APC_CALLBACK_FUNCTION {

    void apply(int _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2);
    static MemorySegment allocate(APC_CALLBACK_FUNCTION fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$496.const$4, fi, constants$496.const$3, scope);
    }
    static APC_CALLBACK_FUNCTION ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2) -> {
            try {
                constants$496.const$5.invokeExact(symbol, __x0, __x1, __x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


