// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1136 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1136() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(PROPENUMPROC.class, "apply", constants$37.const$3);
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(PROPENUMPROCEX.class, "apply", constants$707.const$4);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(EDITWORDBREAKPROC.class, "apply", constants$775.const$4);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(NAMEENUMPROCA.class, "apply", constants$39.const$3);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(NAMEENUMPROCW.class, "apply", constants$39.const$3);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(WINSTAENUMPROCA.class, "apply", constants$39.const$3);
}


