// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3628 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3628() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "CoInitialize",
        constants$18.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "CoRegisterMallocSpy",
        constants$18.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "CoRevokeMallocSpy",
        constants$1.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "CoCreateStandardMalloc",
        constants$12.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "CoRegisterInitializeSpy",
        constants$34.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                JAVA_INT.withName("LowPart"),
                JAVA_INT.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("LowPart"),
                JAVA_INT.withName("HighPart")
            ).withName("u"),
            JAVA_LONG.withName("QuadPart")
        ).withName("_ULARGE_INTEGER")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "CoRevokeInitializeSpy",
        constants$3628.const$5
    );
}


