// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3878 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3878() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(IXMLDOMTextVtbl.get_nodeTypeString.class, "apply", constants$34.const$0);
    static final VarHandle const$1 = constants$3869.const$3.varHandle(MemoryLayout.PathElement.groupElement("get_nodeTypeString"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(IXMLDOMTextVtbl.get_text.class, "apply", constants$34.const$0);
    static final VarHandle const$3 = constants$3869.const$3.varHandle(MemoryLayout.PathElement.groupElement("get_text"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(IXMLDOMTextVtbl.put_text.class, "apply", constants$34.const$0);
    static final VarHandle const$5 = constants$3869.const$3.varHandle(MemoryLayout.PathElement.groupElement("put_text"));
}


