// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1377 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1377() {}
    static final VarHandle const$0 = constants$1376.const$1.varHandle(MemoryLayout.PathElement.groupElement("cxWindowBorders"));
    static final VarHandle const$1 = constants$1376.const$1.varHandle(MemoryLayout.PathElement.groupElement("cyWindowBorders"));
    static final VarHandle const$2 = constants$1376.const$1.varHandle(MemoryLayout.PathElement.groupElement("atomWindowType"));
    static final VarHandle const$3 = constants$1376.const$1.varHandle(MemoryLayout.PathElement.groupElement("wCreatorVersion"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetWindowInfo",
        constants$34.const$0
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("cbSize"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("left"),
            JAVA_INT.withName("top"),
            JAVA_INT.withName("right"),
            JAVA_INT.withName("bottom")
        ).withName("rcTitleBar"),
        MemoryLayout.sequenceLayout(6, JAVA_INT).withName("rgstate")
    ).withName("tagTITLEBARINFO");
}


