// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4017 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4017() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(IXTLRuntimeVtbl.get_definition.class, "apply", constants$34.const$0);
    static final VarHandle const$1 = constants$4007.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_definition"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(IXTLRuntimeVtbl.get_nodeTypedValue.class, "apply", constants$34.const$0);
    static final VarHandle const$3 = constants$4007.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_nodeTypedValue"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(IXTLRuntimeVtbl.put_nodeTypedValue.class, "apply", constants$3752.const$1);
    static final VarHandle const$5 = constants$4007.const$1.varHandle(MemoryLayout.PathElement.groupElement("put_nodeTypedValue"));
}


