// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3771 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3771() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(IXMLDOMDocumentFragmentVtbl.get_attributes.class, "apply", constants$34.const$0);
    static final VarHandle const$1 = constants$3765.const$1.varHandle(MemoryLayout.PathElement.groupElement("get_attributes"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(IXMLDOMDocumentFragmentVtbl.insertBefore.class, "apply", constants$3755.const$3);
    static final VarHandle const$3 = constants$3765.const$1.varHandle(MemoryLayout.PathElement.groupElement("insertBefore"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(IXMLDOMDocumentFragmentVtbl.replaceChild.class, "apply", constants$1.const$3);
    static final VarHandle const$5 = constants$3765.const$1.varHandle(MemoryLayout.PathElement.groupElement("replaceChild"));
}


