// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2280 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2280() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(USER_MARSHAL_FREEING_ROUTINE.class, "apply", constants$469.const$2);
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("pfnBufferSize"),
        RuntimeHelper.POINTER.withName("pfnMarshall"),
        RuntimeHelper.POINTER.withName("pfnUnmarshall"),
        RuntimeHelper.POINTER.withName("pfnFree")
    ).withName("_USER_MARSHAL_ROUTINE_QUADRUPLE");
    static final VarHandle const$2 = constants$2280.const$1.varHandle(MemoryLayout.PathElement.groupElement("pfnBufferSize"));
    static final VarHandle const$3 = constants$2280.const$1.varHandle(MemoryLayout.PathElement.groupElement("pfnMarshall"));
    static final VarHandle const$4 = constants$2280.const$1.varHandle(MemoryLayout.PathElement.groupElement("pfnUnmarshall"));
    static final VarHandle const$5 = constants$2280.const$1.varHandle(MemoryLayout.PathElement.groupElement("pfnFree"));
}


