// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$845 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$845() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "LocalSystemTimeToLocalFileTime",
        constants$37.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SetSystemPowerState",
        constants$12.const$3
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("ACLineStatus"),
        JAVA_BYTE.withName("BatteryFlag"),
        JAVA_BYTE.withName("BatteryLifePercent"),
        JAVA_BYTE.withName("SystemStatusFlag"),
        JAVA_INT.withName("BatteryLifeTime"),
        JAVA_INT.withName("BatteryFullLifeTime")
    ).withName("_SYSTEM_POWER_STATUS");
    static final VarHandle const$3 = constants$845.const$2.varHandle(MemoryLayout.PathElement.groupElement("ACLineStatus"));
    static final VarHandle const$4 = constants$845.const$2.varHandle(MemoryLayout.PathElement.groupElement("BatteryFlag"));
    static final VarHandle const$5 = constants$845.const$2.varHandle(MemoryLayout.PathElement.groupElement("BatteryLifePercent"));
}


