// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$172 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$172() {}
    static final VarHandle const$0 = constants$170.const$1.varHandle(MemoryLayout.PathElement.groupElement("SecurityAttributes"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(30, JAVA_BYTE).withName("PerUserPolicy")
    ).withName("_TOKEN_AUDIT_POLICY");
    static final StructLayout const$2 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(8, JAVA_BYTE).withName("SourceName"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("LowPart"),
            JAVA_INT.withName("HighPart")
        ).withName("SourceIdentifier")
    ).withName("_TOKEN_SOURCE");
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("LowPart"),
            JAVA_INT.withName("HighPart")
        ).withName("TokenId"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("LowPart"),
            JAVA_INT.withName("HighPart")
        ).withName("AuthenticationId"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                JAVA_INT.withName("LowPart"),
                JAVA_INT.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("LowPart"),
                JAVA_INT.withName("HighPart")
            ).withName("u"),
            JAVA_LONG.withName("QuadPart")
        ).withName("ExpirationTime"),
        JAVA_INT.withName("TokenType"),
        JAVA_INT.withName("ImpersonationLevel"),
        JAVA_INT.withName("DynamicCharged"),
        JAVA_INT.withName("DynamicAvailable"),
        JAVA_INT.withName("GroupCount"),
        JAVA_INT.withName("PrivilegeCount"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("LowPart"),
            JAVA_INT.withName("HighPart")
        ).withName("ModifiedId")
    ).withName("_TOKEN_STATISTICS");
    static final VarHandle const$4 = constants$172.const$3.varHandle(MemoryLayout.PathElement.groupElement("TokenType"));
    static final VarHandle const$5 = constants$172.const$3.varHandle(MemoryLayout.PathElement.groupElement("ImpersonationLevel"));
}


