// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2725 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2725() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("Flags"),
        JAVA_INT.withName("NumRanges"),
        MemoryLayout.sequenceLayout(1, MemoryLayout.structLayout(
            JAVA_LONG.withName("StartOffset"),
            JAVA_LONG.withName("LengthInBytes")
        ).withName("_QUERY_BAD_RANGES_INPUT_RANGE")).withName("Ranges")
    ).withName("_QUERY_BAD_RANGES_INPUT");
    static final VarHandle const$1 = constants$2725.const$0.varHandle(MemoryLayout.PathElement.groupElement("Flags"));
    static final VarHandle const$2 = constants$2725.const$0.varHandle(MemoryLayout.PathElement.groupElement("NumRanges"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("Flags"),
        JAVA_INT.withName("Reserved"),
        JAVA_LONG.withName("StartOffset"),
        JAVA_LONG.withName("LengthInBytes")
    ).withName("_QUERY_BAD_RANGES_OUTPUT_RANGE");
    static final VarHandle const$4 = constants$2725.const$3.varHandle(MemoryLayout.PathElement.groupElement("Flags"));
    static final VarHandle const$5 = constants$2725.const$3.varHandle(MemoryLayout.PathElement.groupElement("Reserved"));
}


