// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$751 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$751() {}
    static final VarHandle const$0 = constants$750.const$2.varHandle(MemoryLayout.PathElement.groupElement("dwProviderSubType"));
    static final VarHandle const$1 = constants$750.const$2.varHandle(MemoryLayout.PathElement.groupElement("dwProviderOffset"));
    static final VarHandle const$2 = constants$750.const$2.varHandle(MemoryLayout.PathElement.groupElement("dwProviderSize"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("dwLength"),
        JAVA_INT.withName("dwMemoryLoad"),
        JAVA_LONG.withName("dwTotalPhys"),
        JAVA_LONG.withName("dwAvailPhys"),
        JAVA_LONG.withName("dwTotalPageFile"),
        JAVA_LONG.withName("dwAvailPageFile"),
        JAVA_LONG.withName("dwTotalVirtual"),
        JAVA_LONG.withName("dwAvailVirtual")
    ).withName("_MEMORYSTATUS");
    static final VarHandle const$4 = constants$751.const$3.varHandle(MemoryLayout.PathElement.groupElement("dwLength"));
    static final VarHandle const$5 = constants$751.const$3.varHandle(MemoryLayout.PathElement.groupElement("dwMemoryLoad"));
}


