// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4531 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4531() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ImmGetIMEFileNameW",
        constants$570.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ImmGetProperty",
        constants$65.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ImmIsIME",
        constants$18.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ImmSimulateHotKey",
        constants$65.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ImmCreateContext",
        constants$2.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ImmDestroyContext",
        constants$18.const$5
    );
}


