// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$674 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$674() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "WriteProcessMemory",
        constants$673.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "CreateFileMappingW",
        constants$674.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "OpenFileMappingW",
        constants$624.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "MapViewOfFile",
        constants$674.const$4
    );
}


