// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1528 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1528() {}
    static final VarHandle const$0 = constants$1527.const$3.varHandle(MemoryLayout.PathElement.groupElement("hConvPartner"));
    static final VarHandle const$1 = constants$1527.const$3.varHandle(MemoryLayout.PathElement.groupElement("hszSvcPartner"));
    static final VarHandle const$2 = constants$1527.const$3.varHandle(MemoryLayout.PathElement.groupElement("hszServiceReq"));
    static final VarHandle const$3 = constants$1527.const$3.varHandle(MemoryLayout.PathElement.groupElement("hszTopic"));
    static final VarHandle const$4 = constants$1527.const$3.varHandle(MemoryLayout.PathElement.groupElement("hszItem"));
    static final VarHandle const$5 = constants$1527.const$3.varHandle(MemoryLayout.PathElement.groupElement("wFmt"));
}


