// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4090 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4090() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetClassFileOrMime",
        constants$1499.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IsValidURL",
        constants$570.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "CoGetClassObjectFromURL",
        constants$4090.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "IEInstallScope",
        constants$18.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "FaultInIEFeature",
        constants$607.const$3
    );
}


