// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2687 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2687() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_LONG.withName("SessionId")
    ).withName("_LMR_QUERY_SESSION_INFO");
    static final VarHandle const$1 = constants$2687.const$0.varHandle(MemoryLayout.PathElement.groupElement("SessionId"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_LONG.withName("VetoedFromAltitudeIntegral"),
        JAVA_LONG.withName("VetoedFromAltitudeDecimal"),
        MemoryLayout.sequenceLayout(256, JAVA_SHORT).withName("Reason")
    ).withName("_CSV_QUERY_VETO_FILE_DIRECT_IO_OUTPUT");
    static final VarHandle const$3 = constants$2687.const$2.varHandle(MemoryLayout.PathElement.groupElement("VetoedFromAltitudeIntegral"));
    static final VarHandle const$4 = constants$2687.const$2.varHandle(MemoryLayout.PathElement.groupElement("VetoedFromAltitudeDecimal"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("OwnedByCSVFS")
    ).withName("_CSV_IS_OWNED_BY_CSVFS");
}


