// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4331 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4331() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_propidl_0000_0004_v0_0_c_ifspec", RuntimeHelper.POINTER);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_propidl_0000_0004_v0_0_s_ifspec", RuntimeHelper.POINTER);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "CreateStdProgressIndicator",
        constants$1.const$3
    );
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("IID_StdOle", constants$27.const$0);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SysAllocString",
        constants$33.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SysReAllocString",
        constants$34.const$0
    );
}


