// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4109 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4109() {}
    static final VarHandle const$0 = constants$4107.const$1.varHandle(MemoryLayout.PathElement.groupElement("dwReserved"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("nLength"),
        JAVA_INT.withName("lpSecurityDescriptor"),
        JAVA_INT.withName("bInheritHandle")
    ).withName("_REMSECURITY_ATTRIBUTES");
    static final VarHandle const$2 = constants$4109.const$1.varHandle(MemoryLayout.PathElement.groupElement("nLength"));
    static final VarHandle const$3 = constants$4109.const$1.varHandle(MemoryLayout.PathElement.groupElement("lpSecurityDescriptor"));
    static final VarHandle const$4 = constants$4109.const$1.varHandle(MemoryLayout.PathElement.groupElement("bInheritHandle"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("cbSize"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("szExtraInfo"),
        JAVA_INT.withName("grfBindInfoF"),
        JAVA_INT.withName("dwBindVerb"),
        RuntimeHelper.POINTER.withName("szCustomVerb"),
        JAVA_INT.withName("cbstgmedData"),
        JAVA_INT.withName("dwOptions"),
        JAVA_INT.withName("dwOptionsFlags"),
        JAVA_INT.withName("dwCodePage"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("nLength"),
            JAVA_INT.withName("lpSecurityDescriptor"),
            JAVA_INT.withName("bInheritHandle")
        ).withName("securityAttributes"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("Data1"),
            JAVA_SHORT.withName("Data2"),
            JAVA_SHORT.withName("Data3"),
            MemoryLayout.sequenceLayout(8, JAVA_BYTE).withName("Data4")
        ).withName("iid"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pUnk"),
        JAVA_INT.withName("dwReserved"),
        MemoryLayout.paddingLayout(4)
    ).withName("_tagRemBINDINFO");
}


