// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4190 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4190() {}
    static final VarHandle const$0 = constants$4189.const$5.varHandle(MemoryLayout.PathElement.groupElement("lpVtbl"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IBindHost_RemoteMonikerBindToStorage_Proxy",
        constants$737.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IBindHost_RemoteMonikerBindToStorage_Stub",
        constants$467.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "IBindHost_RemoteMonikerBindToObject_Proxy",
        constants$737.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "IBindHost_RemoteMonikerBindToObject_Stub",
        constants$467.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "HlinkSimpleNavigateToString",
        constants$4190.const$5
    );
}


