// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$800 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$800() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "GetPrivateProfileStructW",
        constants$691.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "WritePrivateProfileStructA",
        constants$691.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "WritePrivateProfileStructW",
        constants$691.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(PGET_SYSTEM_WOW64_DIRECTORY_A.class, "apply", constants$65.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$65.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(PGET_SYSTEM_WOW64_DIRECTORY_W.class, "apply", constants$65.const$2);
}


