// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4133 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4133() {}
    static final VarHandle const$0 = constants$4132.const$0.varHandle(MemoryLayout.PathElement.groupElement("Release"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(IHttpNegotiate2Vtbl.BeginningTransaction.class, "apply", constants$691.const$2);
    static final VarHandle const$2 = constants$4132.const$0.varHandle(MemoryLayout.PathElement.groupElement("BeginningTransaction"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(IHttpNegotiate2Vtbl.OnResponse.class, "apply", constants$775.const$0);
    static final VarHandle const$4 = constants$4132.const$0.varHandle(MemoryLayout.PathElement.groupElement("OnResponse"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(IHttpNegotiate2Vtbl.GetRootSecurityId.class, "apply", constants$707.const$4);
}


