// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$126 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$126() {}
    static final VarHandle const$0 = constants$123.const$2.varHandle(MemoryLayout.PathElement.groupElement("D11"));
    static final VarHandle const$1 = constants$123.const$2.varHandle(MemoryLayout.PathElement.groupElement("D12"));
    static final VarHandle const$2 = constants$123.const$2.varHandle(MemoryLayout.PathElement.groupElement("D13"));
    static final VarHandle const$3 = constants$123.const$2.varHandle(MemoryLayout.PathElement.groupElement("D14"));
    static final VarHandle const$4 = constants$123.const$2.varHandle(MemoryLayout.PathElement.groupElement("D15"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "__int2c",
        constants$0.const$2
    );
}


