// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4197 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4197() {}
    static final VarHandle const$0 = constants$4196.const$0.varHandle(MemoryLayout.PathElement.groupElement("Release"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(IInternetBindInfoVtbl.GetBindInfo.class, "apply", constants$37.const$3);
    static final VarHandle const$2 = constants$4196.const$0.varHandle(MemoryLayout.PathElement.groupElement("GetBindInfo"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(IInternetBindInfoVtbl.GetBindString.class, "apply", constants$703.const$2);
    static final VarHandle const$4 = constants$4196.const$0.varHandle(MemoryLayout.PathElement.groupElement("GetBindString"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("lpVtbl")
    ).withName("IInternetBindInfo");
}


