// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3020 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3020() {}
    static final VarHandle const$0 = constants$3019.const$0.varHandle(MemoryLayout.PathElement.groupElement("Release"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(IMarshal2Vtbl.GetUnmarshalClass.class, "apply", constants$1499.const$2);
    static final VarHandle const$2 = constants$3019.const$0.varHandle(MemoryLayout.PathElement.groupElement("GetUnmarshalClass"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(IMarshal2Vtbl.GetMarshalSizeMax.class, "apply", constants$1499.const$2);
    static final VarHandle const$4 = constants$3019.const$0.varHandle(MemoryLayout.PathElement.groupElement("GetMarshalSizeMax"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(IMarshal2Vtbl.MarshalInterface.class, "apply", constants$1960.const$0);
}


