// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1969 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1969() {}
    static final VarHandle const$0 = constants$1968.const$4.varHandle(MemoryLayout.PathElement.groupElement("dwReserved"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("cContexts"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("rgpszContexts")
    ).withName("_CRYPT_CONTEXTS");
    static final VarHandle const$2 = constants$1969.const$1.varHandle(MemoryLayout.PathElement.groupElement("cContexts"));
    static final VarHandle const$3 = constants$1969.const$1.varHandle(MemoryLayout.PathElement.groupElement("rgpszContexts"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("cFunctions"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("rgpszFunctions")
    ).withName("_CRYPT_CONTEXT_FUNCTIONS");
    static final VarHandle const$5 = constants$1969.const$4.varHandle(MemoryLayout.PathElement.groupElement("cFunctions"));
}


