// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _CONSOLE_SELECTION_INFO CONSOLE_SELECTION_INFO;
 * }
 */
public final class CONSOLE_SELECTION_INFO extends _CONSOLE_SELECTION_INFO {

    // Suppresses default constructor, ensuring non-instantiability.
    private CONSOLE_SELECTION_INFO() {}
}


