// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3176 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3176() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("unused")
    ).withName("MachineGlobalObjectTableRegistrationToken__");
    static final VarHandle const$1 = constants$3176.const$0.varHandle(MemoryLayout.PathElement.groupElement("unused"));
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_objidlbase_0000_0053_v0_0_c_ifspec", RuntimeHelper.POINTER);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_objidlbase_0000_0053_v0_0_s_ifspec", RuntimeHelper.POINTER);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("IID_IMachineGlobalObjectTable", constants$27.const$0);
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("QueryInterface"),
        RuntimeHelper.POINTER.withName("AddRef"),
        RuntimeHelper.POINTER.withName("Release"),
        RuntimeHelper.POINTER.withName("RegisterObject"),
        RuntimeHelper.POINTER.withName("GetObjectA"),
        RuntimeHelper.POINTER.withName("RevokeObject")
    ).withName("IMachineGlobalObjectTableVtbl");
}


