// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1609 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1609() {}
    static final VarHandle const$0 = constants$1607.const$5.varHandle(MemoryLayout.PathElement.groupElement("lpNext"));
    static final VarHandle const$1 = constants$1607.const$5.varHandle(MemoryLayout.PathElement.groupElement("reserved"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_SHORT.withByteAlignment(1).withName("wMid"),
        JAVA_SHORT.withByteAlignment(1).withName("wPid"),
        JAVA_INT.withByteAlignment(1).withName("vDriverVersion"),
        MemoryLayout.sequenceLayout(32, JAVA_BYTE).withName("szPname"),
        JAVA_INT.withByteAlignment(1).withName("dwFormats"),
        JAVA_SHORT.withByteAlignment(1).withName("wChannels"),
        JAVA_SHORT.withByteAlignment(1).withName("wReserved1"),
        JAVA_INT.withByteAlignment(1).withName("dwSupport")
    ).withName("tagWAVEOUTCAPSA");
    static final VarHandle const$3 = constants$1609.const$2.varHandle(MemoryLayout.PathElement.groupElement("wMid"));
    static final VarHandle const$4 = constants$1609.const$2.varHandle(MemoryLayout.PathElement.groupElement("wPid"));
    static final VarHandle const$5 = constants$1609.const$2.varHandle(MemoryLayout.PathElement.groupElement("vDriverVersion"));
}


