// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2711 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2711() {}
    static final VarHandle const$0 = constants$2710.const$4.varHandle(MemoryLayout.PathElement.groupElement("Flags"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("Class"),
            JAVA_INT.withName("Flags")
        ).withName("DesiredStorageClass"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("Length"),
            JAVA_SHORT.withName("Flags"),
            JAVA_INT.withName("Reserved"),
            JAVA_LONG.withName("Vdl")
        ).withName("DataStream"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("Length"),
            JAVA_SHORT.withName("Flags"),
            JAVA_INT.withName("ReparseDataSize"),
            JAVA_INT.withName("ReparseDataOffset")
        ).withName("Reparse"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("Length"),
            JAVA_SHORT.withName("Flags"),
            JAVA_INT.withName("EaSize"),
            JAVA_INT.withName("EaInformationOffset")
        ).withName("Ea")
    ).withName("_StreamInformation");
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("Class"),
        JAVA_INT.withName("Flags")
    ).withName("_DesiredStorageClass");
    static final VarHandle const$3 = constants$2711.const$2.varHandle(MemoryLayout.PathElement.groupElement("Class"));
    static final VarHandle const$4 = constants$2711.const$2.varHandle(MemoryLayout.PathElement.groupElement("Flags"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("Length"),
        JAVA_SHORT.withName("Flags"),
        JAVA_INT.withName("Reserved"),
        JAVA_LONG.withName("Vdl")
    ).withName("_DataStream");
}


