// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1598 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1598() {}
    static final VarHandle const$0 = constants$1597.const$3.varHandle(MemoryLayout.PathElement.groupElement("pIOProc"));
    static final VarHandle const$1 = constants$1597.const$3.varHandle(MemoryLayout.PathElement.groupElement("wErrorRet"));
    static final VarHandle const$2 = constants$1597.const$3.varHandle(MemoryLayout.PathElement.groupElement("htask"));
    static final VarHandle const$3 = constants$1597.const$3.varHandle(MemoryLayout.PathElement.groupElement("cchBuffer"));
    static final VarHandle const$4 = constants$1597.const$3.varHandle(MemoryLayout.PathElement.groupElement("pchBuffer"));
    static final VarHandle const$5 = constants$1597.const$3.varHandle(MemoryLayout.PathElement.groupElement("pchNext"));
}


