// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1112 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1112() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("iType"),
            JAVA_INT.withName("nSize")
        ).withName("emr"),
        JAVA_INT.withName("iEscape"),
        JAVA_INT.withName("cbEscData"),
        MemoryLayout.sequenceLayout(1, JAVA_BYTE).withName("EscData"),
        MemoryLayout.paddingLayout(3)
    ).withName("tagEMREXTESCAPE");
    static final VarHandle const$1 = constants$1112.const$0.varHandle(MemoryLayout.PathElement.groupElement("iEscape"));
    static final VarHandle const$2 = constants$1112.const$0.varHandle(MemoryLayout.PathElement.groupElement("cbEscData"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("iType"),
            JAVA_INT.withName("nSize")
        ).withName("emr"),
        JAVA_INT.withName("iEscape"),
        JAVA_INT.withName("cbDriver"),
        JAVA_INT.withName("cbEscData"),
        MemoryLayout.sequenceLayout(1, JAVA_BYTE).withName("EscData"),
        MemoryLayout.paddingLayout(3)
    ).withName("tagEMRNAMEDESCAPE");
    static final VarHandle const$4 = constants$1112.const$3.varHandle(MemoryLayout.PathElement.groupElement("iEscape"));
    static final VarHandle const$5 = constants$1112.const$3.varHandle(MemoryLayout.PathElement.groupElement("cbDriver"));
}


