// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2428 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2428() {}
    static final VarHandle const$0 = constants$2427.const$3.varHandle(MemoryLayout.PathElement.groupElement("ASCQ"));
    static final VarHandle const$1 = constants$2427.const$3.varHandle(MemoryLayout.PathElement.groupElement("Reserved"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("CriticalHealth"),
        MemoryLayout.sequenceLayout(2, JAVA_BYTE).withName("ModuleHealth"),
        JAVA_BYTE.withName("ErrorThresholdStatus")
    ).withName("");
    static final VarHandle const$3 = constants$2428.const$2.varHandle(MemoryLayout.PathElement.groupElement("CriticalHealth"));
    static final VarHandle const$4 = constants$2428.const$2.varHandle(MemoryLayout.PathElement.groupElement("ErrorThresholdStatus"));
    static final VarHandle const$5 = constants$2427.const$2.varHandle(MemoryLayout.PathElement.groupElement("AsUlong"));
}


