// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4209 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4209() {}
    static final VarHandle const$0 = constants$4207.const$2.varHandle(MemoryLayout.PathElement.groupElement("Continue"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(IInternetProtocolVtbl.Abort.class, "apply", constants$67.const$1);
    static final VarHandle const$2 = constants$4207.const$2.varHandle(MemoryLayout.PathElement.groupElement("Abort"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(IInternetProtocolVtbl.Terminate.class, "apply", constants$65.const$2);
    static final VarHandle const$4 = constants$4207.const$2.varHandle(MemoryLayout.PathElement.groupElement("Terminate"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(IInternetProtocolVtbl.Suspend.class, "apply", constants$18.const$5);
}


