// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2290 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2290() {}
    static final VarHandle const$0 = constants$2287.const$5.varHandle(MemoryLayout.PathElement.groupElement("aXmitQuintuple"));
    static final VarHandle const$1 = constants$2287.const$5.varHandle(MemoryLayout.PathElement.groupElement("pFormatTypes"));
    static final VarHandle const$2 = constants$2287.const$5.varHandle(MemoryLayout.PathElement.groupElement("fCheckBounds"));
    static final VarHandle const$3 = constants$2287.const$5.varHandle(MemoryLayout.PathElement.groupElement("Version"));
    static final VarHandle const$4 = constants$2287.const$5.varHandle(MemoryLayout.PathElement.groupElement("pMallocFreeStruct"));
    static final VarHandle const$5 = constants$2287.const$5.varHandle(MemoryLayout.PathElement.groupElement("MIDLVersion"));
}


