// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$190 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$190() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("NumberOfTargets"),
        JAVA_SHORT.withName("Reserved"),
        JAVA_INT.withName("Reserved2"),
        RuntimeHelper.POINTER.withName("Targets")
    ).withName("_PROCESS_DYNAMIC_EH_CONTINUATION_TARGETS_INFORMATION");
    static final VarHandle const$1 = constants$190.const$0.varHandle(MemoryLayout.PathElement.groupElement("NumberOfTargets"));
    static final VarHandle const$2 = constants$190.const$0.varHandle(MemoryLayout.PathElement.groupElement("Reserved"));
    static final VarHandle const$3 = constants$190.const$0.varHandle(MemoryLayout.PathElement.groupElement("Reserved2"));
    static final VarHandle const$4 = constants$190.const$0.varHandle(MemoryLayout.PathElement.groupElement("Targets"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_LONG.withName("BaseAddress"),
        JAVA_LONG.withName("Size"),
        JAVA_INT.withName("Flags"),
        MemoryLayout.paddingLayout(4)
    ).withName("_PROCESS_DYNAMIC_ENFORCED_ADDRESS_RANGE");
}


