// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$230 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$230() {}
    static final VarHandle const$0 = constants$229.const$5.varHandle(MemoryLayout.PathElement.groupElement("ProcessorMask"));
    static final VarHandle const$1 = constants$229.const$5.varHandle(MemoryLayout.PathElement.groupElement("Relationship"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("Flags")
    ).withName("");
    static final VarHandle const$3 = constants$230.const$2.varHandle(MemoryLayout.PathElement.groupElement("Flags"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("NodeNumber")
    ).withName("");
    static final VarHandle const$5 = constants$230.const$4.varHandle(MemoryLayout.PathElement.groupElement("NodeNumber"));
}


