// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4625 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4625() {}
    static final MemorySegment const$0 = MemorySegment.ofAddress(67L);
    static final MemorySegment const$1 = MemorySegment.ofAddress(68L);
    static final MemorySegment const$2 = MemorySegment.ofAddress(69L);
    static final MemorySegment const$3 = MemorySegment.ofAddress(70L);
    static final MemorySegment const$4 = MemorySegment.ofAddress(71L);
    static final MemorySegment const$5 = MemorySegment.ofAddress(72L);
}


