// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1886 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1886() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "ShellMessageBoxW",
        constants$616.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IsLFNDriveA",
        constants$18.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IsLFNDriveW",
        constants$18.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SHEnumerateUnreadMailAccountsA",
        constants$590.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SHEnumerateUnreadMailAccountsW",
        constants$590.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SHGetUnreadMailCountA",
        constants$807.const$2
    );
}


