// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4084 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4084() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("CLSID_SBS_FileProtocol", constants$27.const$0);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("CLSID_SBS_MkProtocol", constants$27.const$0);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("CLSID_SBS_UrlMkBindCtx", constants$27.const$0);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("CLSID_SBS_SoftDistExt", constants$27.const$0);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("CLSID_SBS_CdlProtocol", constants$27.const$0);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("CLSID_SBS_ClassInstallFilter", constants$27.const$0);
}


