// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2241 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2241() {}
    static final VarHandle const$0 = constants$2240.const$2.varHandle(MemoryLayout.PathElement.groupElement("rgExtension"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "CryptRetrieveTimeStamp",
        constants$2241.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "CryptVerifyTimeStampSignature",
        constants$2235.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(PFN_CRYPT_OBJECT_LOCATOR_PROVIDER_FLUSH.class, "apply", constants$570.const$5);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(PFN_CRYPT_OBJECT_LOCATOR_PROVIDER_GET.class, "apply", constants$717.const$2);
}


