// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4003 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4003() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(IXMLDOMParseErrorVtbl.GetTypeInfoCount.class, "apply", constants$34.const$0);
    static final VarHandle const$1 = constants$4001.const$5.varHandle(MemoryLayout.PathElement.groupElement("GetTypeInfoCount"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(IXMLDOMParseErrorVtbl.GetTypeInfo.class, "apply", constants$644.const$5);
    static final VarHandle const$3 = constants$4001.const$5.varHandle(MemoryLayout.PathElement.groupElement("GetTypeInfo"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(IXMLDOMParseErrorVtbl.GetIDsOfNames.class, "apply", constants$836.const$2);
    static final VarHandle const$5 = constants$4001.const$5.varHandle(MemoryLayout.PathElement.groupElement("GetIDsOfNames"));
}


