// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2581 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2581() {}
    static final VarHandle const$0 = constants$2580.const$5.varHandle(MemoryLayout.PathElement.groupElement("NextEntryOffset"));
    static final VarHandle const$1 = constants$2580.const$5.varHandle(MemoryLayout.PathElement.groupElement("FileIndex"));
    static final VarHandle const$2 = constants$2580.const$5.varHandle(MemoryLayout.PathElement.groupElement("FileNameLength"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_LONG.withName("StartFileReferenceNumber"),
        JAVA_LONG.withName("LowUsn"),
        JAVA_LONG.withName("HighUsn")
    ).withName("");
    static final VarHandle const$4 = constants$2581.const$3.varHandle(MemoryLayout.PathElement.groupElement("StartFileReferenceNumber"));
    static final VarHandle const$5 = constants$2581.const$3.varHandle(MemoryLayout.PathElement.groupElement("LowUsn"));
}


