// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2443 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2443() {}
    static final VarHandle const$0 = constants$2441.const$5.varHandle(MemoryLayout.PathElement.groupElement("ReservedStatus"));
    static final VarHandle const$1 = constants$2441.const$5.varHandle(MemoryLayout.PathElement.groupElement("OutputBlockOffset"));
    static final VarHandle const$2 = constants$2441.const$5.varHandle(MemoryLayout.PathElement.groupElement("OutputBlockLength"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("Action"),
        JAVA_BYTE.withName("SingleRange"),
        MemoryLayout.paddingLayout(3),
        JAVA_INT.withName("ParameterBlockAlignment"),
        JAVA_INT.withName("ParameterBlockLength"),
        JAVA_BYTE.withName("HasOutput"),
        MemoryLayout.paddingLayout(3),
        JAVA_INT.withName("OutputBlockAlignment"),
        JAVA_INT.withName("OutputBlockLength")
    ).withName("_DEVICE_DSM_DEFINITION");
    static final VarHandle const$4 = constants$2443.const$3.varHandle(MemoryLayout.PathElement.groupElement("Action"));
    static final VarHandle const$5 = constants$2443.const$3.varHandle(MemoryLayout.PathElement.groupElement("SingleRange"));
}


