// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2149 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2149() {}
    static final VarHandle const$0 = constants$2148.const$5.varHandle(MemoryLayout.PathElement.groupElement("cbSize"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("cbSize"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pszOpenStoreProvider"),
        JAVA_INT.withName("dwOpenEncodingType"),
        JAVA_INT.withName("dwOpenFlags"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("cbData"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("pbData")
        ).withName("OpenParameters"),
        JAVA_INT.withName("dwFlags"),
        JAVA_INT.withName("dwPriority")
    ).withName("_CERT_PHYSICAL_STORE_INFO");
    static final VarHandle const$2 = constants$2149.const$1.varHandle(MemoryLayout.PathElement.groupElement("cbSize"));
    static final VarHandle const$3 = constants$2149.const$1.varHandle(MemoryLayout.PathElement.groupElement("pszOpenStoreProvider"));
    static final VarHandle const$4 = constants$2149.const$1.varHandle(MemoryLayout.PathElement.groupElement("dwOpenEncodingType"));
    static final VarHandle const$5 = constants$2149.const$1.varHandle(MemoryLayout.PathElement.groupElement("dwOpenFlags"));
}


