// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4346 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4346() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "VarI2FromStr",
        constants$644.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "VarI2FromDisp",
        constants$485.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "VarI2FromBool",
        constants$7.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "VarI2FromI1",
        constants$862.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "VarI2FromUI2",
        constants$7.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "VarI2FromUI4",
        constants$12.const$0
    );
}


