// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3273 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3273() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "IStorage_RemoteCopyTo_Stub",
        constants$467.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "IStorage_RemoteEnumElements_Proxy",
        constants$1008.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "IStorage_RemoteEnumElements_Stub",
        constants$467.const$0
    );
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_objidl_0000_0066_v0_0_c_ifspec", RuntimeHelper.POINTER);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_objidl_0000_0066_v0_0_s_ifspec", RuntimeHelper.POINTER);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("IID_IPersistFile", constants$27.const$0);
}


