// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _CRYPT_X942_OTHER_INFO CRYPT_X942_OTHER_INFO;
 * }
 */
public final class CRYPT_X942_OTHER_INFO extends _CRYPT_X942_OTHER_INFO {

    // Suppresses default constructor, ensuring non-instantiability.
    private CRYPT_X942_OTHER_INFO() {}
}


