// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _CTL_FIND_SUBJECT_PARA CTL_FIND_SUBJECT_PARA;
 * }
 */
public final class CTL_FIND_SUBJECT_PARA extends _CTL_FIND_SUBJECT_PARA {

    // Suppresses default constructor, ensuring non-instantiability.
    private CTL_FIND_SUBJECT_PARA() {}
}


