// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _DEVICE_MANAGE_DATA_SET_ATTRIBUTES DEVICE_MANAGE_DATA_SET_ATTRIBUTES;
 * }
 */
public final class DEVICE_MANAGE_DATA_SET_ATTRIBUTES extends _DEVICE_MANAGE_DATA_SET_ATTRIBUTES {

    // Suppresses default constructor, ensuring non-instantiability.
    private DEVICE_MANAGE_DATA_SET_ATTRIBUTES() {}
}


