// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * unsigned long (*DRIVERMSGPROC)(unsigned long,unsigned long,unsigned long long,unsigned long long,unsigned long long);
 * }
 */
public interface DRIVERMSGPROC {

    int apply(int _x0, int _x1, long _x2, long _x3, long _x4);
    static MemorySegment allocate(DRIVERMSGPROC fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$1596.const$2, fi, constants$1596.const$1, scope);
    }
    static DRIVERMSGPROC ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int __x0, int __x1, long __x2, long __x3, long __x4) -> {
            try {
                return (int)constants$1596.const$3.invokeExact(symbol, __x0, __x1, __x2, __x3, __x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


