// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _FILE_STORAGE_TIER_REGION FILE_STORAGE_TIER_REGION;
 * }
 */
public final class FILE_STORAGE_TIER_REGION extends _FILE_STORAGE_TIER_REGION {

    // Suppresses default constructor, ensuring non-instantiability.
    private FILE_STORAGE_TIER_REGION() {}
}


