// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _FILE_END_OF_FILE_INFO FILE_END_OF_FILE_INFO;
 * }
 */
public final class FILE_END_OF_FILE_INFO extends _FILE_END_OF_FILE_INFO {

    // Suppresses default constructor, ensuring non-instantiability.
    private FILE_END_OF_FILE_INFO() {}
}


