// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _FORM_INFO_2A FORM_INFO_2;
 * }
 */
public final class FORM_INFO_2 extends _FORM_INFO_2A {

    // Suppresses default constructor, ensuring non-instantiability.
    private FORM_INFO_2() {}
}


