// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _MONITOR_INFO_1A MONITOR_INFO_1;
 * }
 */
public final class MONITOR_INFO_1 extends _MONITOR_INFO_1A {

    // Suppresses default constructor, ensuring non-instantiability.
    private MONITOR_INFO_1() {}
}


