// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _PHYSICAL_ELEMENT_STATUS PHYSICAL_ELEMENT_STATUS;
 * }
 */
public final class PHYSICAL_ELEMENT_STATUS extends _PHYSICAL_ELEMENT_STATUS {

    // Suppresses default constructor, ensuring non-instantiability.
    private PHYSICAL_ELEMENT_STATUS() {}
}


