// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _PROPSHEETPAGEW PROPSHEETPAGEW_LATEST;
 * }
 */
public final class PROPSHEETPAGEW_LATEST extends _PROPSHEETPAGEW {

    // Suppresses default constructor, ensuring non-instantiability.
    private PROPSHEETPAGEW_LATEST() {}
}


