// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _RPC_SECURITY_QOS_V4_A RPC_SECURITY_QOS_V4_A;
 * }
 */
public final class RPC_SECURITY_QOS_V4_A extends _RPC_SECURITY_QOS_V4_A {

    // Suppresses default constructor, ensuring non-instantiability.
    private RPC_SECURITY_QOS_V4_A() {}
}


