// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _SESSION_HEADER SESSION_HEADER;
 * }
 */
public final class SESSION_HEADER extends _SESSION_HEADER {

    // Suppresses default constructor, ensuring non-instantiability.
    private SESSION_HEADER() {}
}


