// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _TOKEN_USER_CLAIMS TOKEN_USER_CLAIMS;
 * }
 */
public final class TOKEN_USER_CLAIMS extends _TOKEN_USER_CLAIMS {

    // Suppresses default constructor, ensuring non-instantiability.
    private TOKEN_USER_CLAIMS() {}
}


