// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _AppBarData {
 *     DWORD cbSize;
 *     HWND hWnd;
 *     UINT uCallbackMessage;
 *     UINT uEdge;
 *     RECT rc;
 *     LPARAM lParam;
 * } APPBARDATA
 * }
 */
public class APPBARDATA extends _AppBarData {

    APPBARDATA() {
        // Should not be called directly
    }
}

