// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _CERT_POLICY_ID {
 *     DWORD cCertPolicyElementId;
 *     LPSTR *rgpszCertPolicyElementId;
 * } CERT_POLICY_ID
 * }
 */
public class CERT_POLICY_ID extends _CERT_POLICY_ID {

    CERT_POLICY_ID() {
        // Should not be called directly
    }
}

