// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _CERT_STORE_PROV_INFO {
 *     DWORD cbSize;
 *     DWORD cStoreProvFunc;
 *     void **rgpvStoreProvFunc;
 *     HCERTSTOREPROV hStoreProv;
 *     DWORD dwStoreProvFlags;
 *     HCRYPTOIDFUNCADDR hStoreProvFuncAddr2;
 * } CERT_STORE_PROV_INFO
 * }
 */
public class CERT_STORE_PROV_INFO extends _CERT_STORE_PROV_INFO {

    CERT_STORE_PROV_INFO() {
        // Should not be called directly
    }
}

