// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _CERT_GENERAL_SUBTREE {
 *     CERT_ALT_NAME_ENTRY Base;
 *     DWORD dwMinimum;
 *     BOOL fMaximum;
 *     DWORD dwMaximum;
 * } CERT_GENERAL_SUBTREE
 * }
 */
public class CERT_GENERAL_SUBTREE extends _CERT_GENERAL_SUBTREE {

    CERT_GENERAL_SUBTREE() {
        // Should not be called directly
    }
}

