// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef CONNECTDLGSTRUCTA CONNECTDLGSTRUCT
 * }
 */
public class CONNECTDLGSTRUCT extends _CONNECTDLGSTRUCTA {

    CONNECTDLGSTRUCT() {
        // Should not be called directly
    }
}

