// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _CRYPT_VERIFY_CERT_SIGN_WEAK_HASH_INFO {
 *     DWORD cCNGHashAlgid;
 *     PCWSTR *rgpwszCNGHashAlgid;
 *     DWORD dwWeakIndex;
 * } CRYPT_VERIFY_CERT_SIGN_WEAK_HASH_INFO
 * }
 */
public class CRYPT_VERIFY_CERT_SIGN_WEAK_HASH_INFO extends _CRYPT_VERIFY_CERT_SIGN_WEAK_HASH_INFO {

    CRYPT_VERIFY_CERT_SIGN_WEAK_HASH_INFO() {
        // Should not be called directly
    }
}

