// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _CRYPT_HASH_MESSAGE_PARA {
 *     DWORD cbSize;
 *     DWORD dwMsgEncodingType;
 *     HCRYPTPROV_LEGACY hCryptProv;
 *     CRYPT_ALGORITHM_IDENTIFIER HashAlgorithm;
 *     void *pvHashAuxInfo;
 * } CRYPT_HASH_MESSAGE_PARA
 * }
 */
public class CRYPT_HASH_MESSAGE_PARA extends _CRYPT_HASH_MESSAGE_PARA {

    CRYPT_HASH_MESSAGE_PARA() {
        // Should not be called directly
    }
}

