// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _DEVICE_DSM_OFFLOAD_WRITE_PARAMETERS {
 *     DWORD Flags;
 *     DWORD Reserved;
 *     DWORDLONG TokenOffset;
 *     STORAGE_OFFLOAD_TOKEN Token;
 * } DEVICE_DSM_OFFLOAD_WRITE_PARAMETERS
 * }
 */
public class DEVICE_DSM_OFFLOAD_WRITE_PARAMETERS extends _DEVICE_DSM_OFFLOAD_WRITE_PARAMETERS {

    DEVICE_DSM_OFFLOAD_WRITE_PARAMETERS() {
        // Should not be called directly
    }
}

