// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef DISCDLGSTRUCTA DISCDLGSTRUCT
 * }
 */
public class DISCDLGSTRUCT extends _DISCDLGSTRUCTA {

    DISCDLGSTRUCT() {
        // Should not be called directly
    }
}

