// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef union _DISPATCHER_CONTEXT_NONVOLREG_ARM64 {
 *     BYTE Buffer[152];
 *     struct {
 *         DWORD64 GpNvRegs[11];
 *         double FpNvRegs[8];
 *     };
 * } DISPATCHER_CONTEXT_NONVOLREG_ARM64
 * }
 */
public class DISPATCHER_CONTEXT_NONVOLREG_ARM64 extends _DISPATCHER_CONTEXT_NONVOLREG_ARM64 {

    DISPATCHER_CONTEXT_NONVOLREG_ARM64() {
        // Should not be called directly
    }
}

