// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagABORTPATH {
 *     EMR emr;
 * } EMRENDPATH
 * }
 */
public class EMRENDPATH extends tagABORTPATH {

    EMRENDPATH() {
        // Should not be called directly
    }
}

