// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagEMRLINETO {
 *     EMR emr;
 *     POINTL ptl;
 * } EMRMOVETOEX
 * }
 */
public class EMRMOVETOEX extends tagEMRLINETO {

    EMRMOVETOEX() {
        // Should not be called directly
    }
}

