// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagEMRNAMEDESCAPE {
 *     EMR emr;
 *     INT iEscape;
 *     INT cbDriver;
 *     INT cbEscData;
 *     BYTE EscData[1];
 * } EMRNAMEDESCAPE
 * }
 */
public class EMRNAMEDESCAPE extends tagEMRNAMEDESCAPE {

    EMRNAMEDESCAPE() {
        // Should not be called directly
    }
}

