// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _ENCLAVE_LOAD_DATA_VBS_BASIC {
 *     DWORD PageType;
 * } ENCLAVE_LOAD_DATA_VBS_BASIC
 * }
 */
public class ENCLAVE_LOAD_DATA_VBS_BASIC extends _ENCLAVE_LOAD_DATA_VBS_BASIC {

    ENCLAVE_LOAD_DATA_VBS_BASIC() {
        // Should not be called directly
    }
}

