// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct fd_set {
 *     u_int fd_count;
 *     SOCKET fd_array[64];
 * } FD_SET
 * }
 */
public class FD_SET$13 extends fd_set {

    FD_SET$13() {
        // Should not be called directly
    }
}

