// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _FILESYSTEM_STATISTICS_EX {
 *     WORD FileSystemType;
 *     WORD Version;
 *     DWORD SizeOfCompleteStructure;
 *     DWORDLONG UserFileReads;
 *     DWORDLONG UserFileReadBytes;
 *     DWORDLONG UserDiskReads;
 *     DWORDLONG UserFileWrites;
 *     DWORDLONG UserFileWriteBytes;
 *     DWORDLONG UserDiskWrites;
 *     DWORDLONG MetaDataReads;
 *     DWORDLONG MetaDataReadBytes;
 *     DWORDLONG MetaDataDiskReads;
 *     DWORDLONG MetaDataWrites;
 *     DWORDLONG MetaDataWriteBytes;
 *     DWORDLONG MetaDataDiskWrites;
 * } FILESYSTEM_STATISTICS_EX
 * }
 */
public class FILESYSTEM_STATISTICS_EX extends _FILESYSTEM_STATISTICS_EX {

    FILESYSTEM_STATISTICS_EX() {
        // Should not be called directly
    }
}

