// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _GENERIC_MAPPING {
 *     ACCESS_MASK GenericRead;
 *     ACCESS_MASK GenericWrite;
 *     ACCESS_MASK GenericExecute;
 *     ACCESS_MASK GenericAll;
 * } GENERIC_MAPPING
 * }
 */
public class GENERIC_MAPPING extends _GENERIC_MAPPING {

    GENERIC_MAPPING() {
        // Should not be called directly
    }
}

