// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagICONMETRICSW {
 *     UINT cbSize;
 *     int iHorzSpacing;
 *     int iVertSpacing;
 *     int iTitleWrap;
 *     LOGFONTW lfFont;
 * } ICONMETRICSW
 * }
 */
public class ICONMETRICSW extends tagICONMETRICSW {

    ICONMETRICSW() {
        // Should not be called directly
    }
}

