// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef ICONINFOEXA ICONINFOEX
 * }
 */
public class ICONINFOEX extends _ICONINFOEXA {

    ICONINFOEX() {
        // Should not be called directly
    }
}

