// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef union _IMAGE_AUX_SYMBOL_EX {
 *     struct {
 *         DWORD WeakDefaultSymIndex;
 *         DWORD WeakSearchType;
 *         BYTE rgbReserved[12];
 *     } Sym;
 *     struct {
 *         BYTE Name[20];
 *     } File;
 *     struct {
 *         DWORD Length;
 *         WORD NumberOfRelocations;
 *         WORD NumberOfLinenumbers;
 *         DWORD CheckSum;
 *         SHORT Number;
 *         BYTE Selection;
 *         BYTE bReserved;
 *         SHORT HighNumber;
 *         BYTE rgbReserved[2];
 *     } Section;
 *     struct {
 *         IMAGE_AUX_SYMBOL_TOKEN_DEF TokenDef;
 *         BYTE rgbReserved[2];
 *     };
 *     struct {
 *         DWORD crc;
 *         BYTE rgbReserved[16];
 *     } CRC;
 * } IMAGE_AUX_SYMBOL_EX
 * }
 */
public class IMAGE_AUX_SYMBOL_EX extends _IMAGE_AUX_SYMBOL_EX {

    IMAGE_AUX_SYMBOL_EX() {
        // Should not be called directly
    }
}

