// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef RTL_RUN_ONCE INIT_ONCE
 * }
 */
public class INIT_ONCE extends _RTL_RUN_ONCE {

    INIT_ONCE() {
        // Should not be called directly
    }
}

