// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef JOB_INFO_1A JOB_INFO_1
 * }
 */
public class JOB_INFO_1 extends _JOB_INFO_1A {

    JOB_INFO_1() {
        // Should not be called directly
    }
}

