// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagMCI_INFO_PARMSA {
 *     DWORD_PTR dwCallback;
 *     LPSTR lpstrReturn;
 *     DWORD dwRetSize;
 * } MCI_INFO_PARMSA
 * }
 */
public class MCI_INFO_PARMSA extends tagMCI_INFO_PARMSA {

    MCI_INFO_PARMSA() {
        // Should not be called directly
    }
}

