// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagMCI_OVLY_OPEN_PARMSW {
 *     DWORD_PTR dwCallback;
 *     MCIDEVICEID wDeviceID;
 *     LPCWSTR lpstrDeviceType;
 *     LPCWSTR lpstrElementName;
 *     LPCWSTR lpstrAlias;
 *     DWORD dwStyle;
 *     HWND hWndParent;
 * } MCI_OVLY_OPEN_PARMSW
 * }
 */
public class MCI_OVLY_OPEN_PARMSW extends tagMCI_OVLY_OPEN_PARMSW {

    MCI_OVLY_OPEN_PARMSW() {
        // Should not be called directly
    }
}

