// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagMENUGETOBJECTINFO {
 *     DWORD dwFlags;
 *     UINT uPos;
 *     HMENU hmenu;
 *     PVOID riid;
 *     PVOID pvObj;
 * } MENUGETOBJECTINFO
 * }
 */
public class MENUGETOBJECTINFO extends tagMENUGETOBJECTINFO {

    MENUGETOBJECTINFO() {
        // Should not be called directly
    }
}

