// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagMIDIINCAPS2W {
 *     WORD wMid;
 *     WORD wPid;
 *     MMVERSION vDriverVersion;
 *     WCHAR szPname[32];
 *     DWORD dwSupport;
 *     GUID ManufacturerGuid;
 *     GUID ProductGuid;
 *     GUID NameGuid;
 * } MIDIINCAPS2W
 * }
 */
public class MIDIINCAPS2W extends tagMIDIINCAPS2W {

    MIDIINCAPS2W() {
        // Should not be called directly
    }
}

