// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _NCRYPT_KEY_ATTEST_PADDING_INFO {
 *     ULONG magic;
 *     PUCHAR pbKeyBlob;
 *     ULONG cbKeyBlob;
 *     PUCHAR pbKeyAuth;
 *     ULONG cbKeyAuth;
 * } NCRYPT_KEY_ATTEST_PADDING_INFO
 * }
 */
public class NCRYPT_KEY_ATTEST_PADDING_INFO extends _NCRYPT_KEY_ATTEST_PADDING_INFO {

    NCRYPT_KEY_ATTEST_PADDING_INFO() {
        // Should not be called directly
    }
}

