// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _NETRESOURCEA {
 *     DWORD dwScope;
 *     DWORD dwType;
 *     DWORD dwDisplayType;
 *     DWORD dwUsage;
 *     LPSTR lpLocalName;
 *     LPSTR lpRemoteName;
 *     LPSTR lpComment;
 *     LPSTR lpProvider;
 * } NETRESOURCEA
 * }
 */
public class NETRESOURCEA extends _NETRESOURCEA {

    NETRESOURCEA() {
        // Should not be called directly
    }
}

