// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef NETRESOURCEA NETRESOURCE
 * }
 */
public class NETRESOURCE extends _NETRESOURCEA {

    NETRESOURCE() {
        // Should not be called directly
    }
}

