// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _OFNOTIFYEXW {
 *     NMHDR hdr;
 *     LPOPENFILENAMEW lpOFN;
 *     LPVOID psf;
 *     LPVOID pidl;
 * } OFNOTIFYEXW
 * }
 */
public class OFNOTIFYEXW extends _OFNOTIFYEXW {

    OFNOTIFYEXW() {
        // Should not be called directly
    }
}

