// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef OFNOTIFYA OFNOTIFY
 * }
 */
public class OFNOTIFY extends _OFNOTIFYA {

    OFNOTIFY() {
        // Should not be called directly
    }
}

