// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef OPENFILENAME_NT4A OPENFILENAME_NT4
 * }
 */
public class OPENFILENAME_NT4 extends tagOFN_NT4A {

    OPENFILENAME_NT4() {
        // Should not be called directly
    }
}

