// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _OPERATION_START_PARAMETERS {
 *     ULONG Version;
 *     OPERATION_ID OperationId;
 *     ULONG Flags;
 * } OPERATION_START_PARAMETERS
 * }
 */
public class OPERATION_START_PARAMETERS extends _OPERATION_START_PARAMETERS {

    OPERATION_START_PARAMETERS() {
        // Should not be called directly
    }
}

