// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _PRINTER_INFO_3 {
 *     PSECURITY_DESCRIPTOR pSecurityDescriptor;
 * } PRINTER_INFO_3
 * }
 */
public class PRINTER_INFO_3 extends _PRINTER_INFO_3 {

    PRINTER_INFO_3() {
        // Should not be called directly
    }
}

