// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _SE_TOKEN_USER {
 *     union {
 *         TOKEN_USER TokenUser;
 *         SID_AND_ATTRIBUTES User;
 *     };
 *     union {
 *         SID Sid;
 *         BYTE Buffer[68];
 *     };
 * } PSE_TOKEN_USER
 * }
 */
public class PSE_TOKEN_USER extends _SE_TOKEN_USER {

    PSE_TOKEN_USER() {
        // Should not be called directly
    }
}

