// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _REASON_CONTEXT {
 *     ULONG Version;
 *     DWORD Flags;
 *     union {
 *         struct {
 *             HMODULE LocalizedReasonModule;
 *             ULONG LocalizedReasonId;
 *             ULONG ReasonStringCount;
 *             LPWSTR *ReasonStrings;
 *         } Detailed;
 *         LPWSTR SimpleReasonString;
 *     } Reason;
 * } REASON_CONTEXT
 * }
 */
public class REASON_CONTEXT extends _REASON_CONTEXT {

    REASON_CONTEXT() {
        // Should not be called directly
    }
}

