// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagRECT {
 *     LONG left;
 *     LONG top;
 *     LONG right;
 *     LONG bottom;
 * } RECT
 * }
 */
public class RECT extends tagRECT {

    RECT() {
        // Should not be called directly
    }
}

