// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct tagRID_DEVICE_INFO {
 *     DWORD cbSize;
 *     DWORD dwType;
 *     union {
 *         RID_DEVICE_INFO_MOUSE mouse;
 *         RID_DEVICE_INFO_KEYBOARD keyboard;
 *         RID_DEVICE_INFO_HID hid;
 *     };
 * } RID_DEVICE_INFO
 * }
 */
public class RID_DEVICE_INFO extends tagRID_DEVICE_INFO {

    RID_DEVICE_INFO() {
        // Should not be called directly
    }
}

