// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _RTL_CONDITION_VARIABLE {
 *     PVOID Ptr;
 * } RTL_CONDITION_VARIABLE
 * }
 */
public class RTL_CONDITION_VARIABLE extends _RTL_CONDITION_VARIABLE {

    RTL_CONDITION_VARIABLE() {
        // Should not be called directly
    }
}

