// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _SESSION_HEADER {
 *     UCHAR sess_name;
 *     UCHAR num_sess;
 *     UCHAR rcv_dg_outstanding;
 *     UCHAR rcv_any_outstanding;
 * } SESSION_HEADER
 * }
 */
public class SESSION_HEADER extends _SESSION_HEADER {

    SESSION_HEADER() {
        // Should not be called directly
    }
}

