// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _HTTPSPolicyCallbackData {
 *     union {
 *         DWORD cbStruct;
 *         DWORD cbSize;
 *     };
 *     DWORD dwAuthType;
 *     DWORD fdwChecks;
 *     WCHAR *pwszServerName;
 * } SSL_EXTRA_CERT_CHAIN_POLICY_PARA
 * }
 */
public class SSL_EXTRA_CERT_CHAIN_POLICY_PARA extends _HTTPSPolicyCallbackData {

    SSL_EXTRA_CERT_CHAIN_POLICY_PARA() {
        // Should not be called directly
    }
}

