// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _STORAGE_OFFLOAD_READ_OUTPUT {
 *     DWORD OffloadReadFlags;
 *     DWORD Reserved;
 *     DWORDLONG LengthProtected;
 *     DWORD TokenLength;
 *     STORAGE_OFFLOAD_TOKEN Token;
 * } STORAGE_OFFLOAD_READ_OUTPUT
 * }
 */
public class STORAGE_OFFLOAD_READ_OUTPUT extends _STORAGE_OFFLOAD_READ_OUTPUT {

    STORAGE_OFFLOAD_READ_OUTPUT() {
        // Should not be called directly
    }
}

