// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _TAPE_CREATE_PARTITION {
 *     DWORD Method;
 *     DWORD Count;
 *     DWORD Size;
 * } TAPE_CREATE_PARTITION
 * }
 */
public class TAPE_CREATE_PARTITION extends _TAPE_CREATE_PARTITION {

    TAPE_CREATE_PARTITION() {
        // Should not be called directly
    }
}

