// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _TAPE_GET_POSITION {
 *     DWORD Type;
 *     DWORD Partition;
 *     LARGE_INTEGER Offset;
 * } TAPE_GET_POSITION
 * }
 */
public class TAPE_GET_POSITION extends _TAPE_GET_POSITION {

    TAPE_GET_POSITION() {
        // Should not be called directly
    }
}

