// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef TEXTMETRICA TEXTMETRIC
 * }
 */
public class TEXTMETRIC extends tagTEXTMETRICA {

    TEXTMETRIC() {
        // Should not be called directly
    }
}

