// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef struct _TOKEN_SID_INFORMATION {
 *     PSID Sid;
 * } TOKEN_SID_INFORMATION
 * }
 */
public class TOKEN_SID_INFORMATION extends _TOKEN_SID_INFORMATION {

    TOKEN_SID_INFORMATION() {
        // Should not be called directly
    }
}

