// Generated by jextract

package com.github.teruteru.windows;

/**
 * {@snippet lang=c :
 * typedef USN_RECORD_V2 USN_RECORD
 * }
 */
public class USN_RECORD extends USN_RECORD_V2 {

    USN_RECORD() {
        // Should not be called directly
    }
}

