// Generated by jextract

package com.twitter.teruteru128.preview.opencl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _cl_mutable_dispatch_exec_info_khr {
 *     cl_uint param_name;
 *     size_t param_value_size;
 *     void* param_value;
 * };
 * }
 */
public class _cl_mutable_dispatch_exec_info_khr {

    public static MemoryLayout $LAYOUT() {
        return constants$220.const$5;
    }
    public static VarHandle param_name$VH() {
        return constants$221.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * cl_uint param_name;
     * }
     */
    public static int param_name$get(MemorySegment seg) {
        return (int)constants$221.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * cl_uint param_name;
     * }
     */
    public static void param_name$set(MemorySegment seg, int x) {
        constants$221.const$0.set(seg, x);
    }
    public static int param_name$get(MemorySegment seg, long index) {
        return (int)constants$221.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void param_name$set(MemorySegment seg, long index, int x) {
        constants$221.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle param_value_size$VH() {
        return constants$221.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t param_value_size;
     * }
     */
    public static long param_value_size$get(MemorySegment seg) {
        return (long)constants$221.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t param_value_size;
     * }
     */
    public static void param_value_size$set(MemorySegment seg, long x) {
        constants$221.const$1.set(seg, x);
    }
    public static long param_value_size$get(MemorySegment seg, long index) {
        return (long)constants$221.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void param_value_size$set(MemorySegment seg, long index, long x) {
        constants$221.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle param_value$VH() {
        return constants$221.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* param_value;
     * }
     */
    public static MemorySegment param_value$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$221.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* param_value;
     * }
     */
    public static void param_value$set(MemorySegment seg, MemorySegment x) {
        constants$221.const$2.set(seg, x);
    }
    public static MemorySegment param_value$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$221.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void param_value$set(MemorySegment seg, long index, MemorySegment x) {
        constants$221.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


