// Generated by jextract

package com.twitter.teruteru128.preview.opencl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*clSetMemObjectDestructorAPPLE_fn)(struct _cl_mem* memobj,void (*pfn_notify)(struct _cl_mem*,void*),void* user_data);
 * }
 */
public interface clSetMemObjectDestructorAPPLE_fn {

    int apply(java.lang.foreign.MemorySegment memobj, java.lang.foreign.MemorySegment pfn_notify, java.lang.foreign.MemorySegment user_data);
    static MemorySegment allocate(clSetMemObjectDestructorAPPLE_fn fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$225.const$2, fi, constants$9.const$0, scope);
    }
    static clSetMemObjectDestructorAPPLE_fn ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _memobj, java.lang.foreign.MemorySegment _pfn_notify, java.lang.foreign.MemorySegment _user_data) -> {
            try {
                return (int)constants$9.const$2.invokeExact(symbol, _memobj, _pfn_notify, _user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


