// Generated by jextract

package com.github.teruteru128.preview.windows;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _STORAGE_CRYPTO_DESCRIPTOR {
 *     DWORD Version;
 *     DWORD Size;
 *     DWORD NumKeysSupported;
 *     DWORD NumCryptoCapabilities;
 *     STORAGE_CRYPTO_CAPABILITY CryptoCapabilities[1];
 * } STORAGE_CRYPTO_DESCRIPTOR
 * }
 */
public class STORAGE_CRYPTO_DESCRIPTOR extends _STORAGE_CRYPTO_DESCRIPTOR {

    STORAGE_CRYPTO_DESCRIPTOR() {
        // Should not be called directly
    }
}

