// Generated by jextract

package com.github.teruteru128.foreign.windows;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _CMC_PEND_INFO {
 *     CRYPT_DATA_BLOB PendToken;
 *     FILETIME PendTime;
 * } CMC_PEND_INFO
 * }
 */
public class CMC_PEND_INFO extends _CMC_PEND_INFO {

    CMC_PEND_INFO() {
        // Should not be called directly
    }
}

