// Generated by jextract

package com.github.teruteru128.foreign.windows;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct tagDISPPARAMS {
 *     VARIANTARG *rgvarg;
 *     DISPID *rgdispidNamedArgs;
 *     UINT cArgs;
 *     UINT cNamedArgs;
 * } DISPPARAMS
 * }
 */
public class DISPPARAMS extends tagDISPPARAMS {

    DISPPARAMS() {
        // Should not be called directly
    }
}

