// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _ACTIVATION_CONTEXT_QUERY_INDEX {
 *     DWORD ulAssemblyIndex;
 *     DWORD ulFileIndexInAssembly;
 * };
 * }
 */
public class _ACTIVATION_CONTEXT_QUERY_INDEX {

    public static MemoryLayout $LAYOUT() {
        return constants$497.const$4;
    }
    public static VarHandle ulAssemblyIndex$VH() {
        return constants$497.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD ulAssemblyIndex;
     * }
     */
    public static int ulAssemblyIndex$get(MemorySegment seg) {
        return (int)constants$497.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD ulAssemblyIndex;
     * }
     */
    public static void ulAssemblyIndex$set(MemorySegment seg, int x) {
        constants$497.const$5.set(seg, x);
    }
    public static int ulAssemblyIndex$get(MemorySegment seg, long index) {
        return (int)constants$497.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void ulAssemblyIndex$set(MemorySegment seg, long index, int x) {
        constants$497.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ulFileIndexInAssembly$VH() {
        return constants$498.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD ulFileIndexInAssembly;
     * }
     */
    public static int ulFileIndexInAssembly$get(MemorySegment seg) {
        return (int)constants$498.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD ulFileIndexInAssembly;
     * }
     */
    public static void ulFileIndexInAssembly$set(MemorySegment seg, int x) {
        constants$498.const$0.set(seg, x);
    }
    public static int ulFileIndexInAssembly$get(MemorySegment seg, long index) {
        return (int)constants$498.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void ulFileIndexInAssembly$set(MemorySegment seg, long index, int x) {
        constants$498.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


