// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _BCryptBuffer {
 *     ULONG cbBuffer;
 *     ULONG BufferType;
 *     PVOID pvBuffer;
 * };
 * }
 */
public class _BCryptBuffer {

    public static MemoryLayout $LAYOUT() {
        return constants$1944.const$1;
    }
    public static VarHandle cbBuffer$VH() {
        return constants$1944.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * ULONG cbBuffer;
     * }
     */
    public static int cbBuffer$get(MemorySegment seg) {
        return (int)constants$1944.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * ULONG cbBuffer;
     * }
     */
    public static void cbBuffer$set(MemorySegment seg, int x) {
        constants$1944.const$2.set(seg, x);
    }
    public static int cbBuffer$get(MemorySegment seg, long index) {
        return (int)constants$1944.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void cbBuffer$set(MemorySegment seg, long index, int x) {
        constants$1944.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle BufferType$VH() {
        return constants$1944.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * ULONG BufferType;
     * }
     */
    public static int BufferType$get(MemorySegment seg) {
        return (int)constants$1944.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * ULONG BufferType;
     * }
     */
    public static void BufferType$set(MemorySegment seg, int x) {
        constants$1944.const$3.set(seg, x);
    }
    public static int BufferType$get(MemorySegment seg, long index) {
        return (int)constants$1944.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void BufferType$set(MemorySegment seg, long index, int x) {
        constants$1944.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pvBuffer$VH() {
        return constants$1944.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PVOID pvBuffer;
     * }
     */
    public static MemorySegment pvBuffer$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$1944.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PVOID pvBuffer;
     * }
     */
    public static void pvBuffer$set(MemorySegment seg, MemorySegment x) {
        constants$1944.const$4.set(seg, x);
    }
    public static MemorySegment pvBuffer$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$1944.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void pvBuffer$set(MemorySegment seg, long index, MemorySegment x) {
        constants$1944.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


