// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _CERT_BIOMETRIC_EXT_INFO {
 *     DWORD cBiometricData;
 *     PCERT_BIOMETRIC_DATA rgBiometricData;
 * };
 * }
 */
public class _CERT_BIOMETRIC_EXT_INFO {

    public static MemoryLayout $LAYOUT() {
        return constants$2064.const$5;
    }
    public static VarHandle cBiometricData$VH() {
        return constants$2065.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD cBiometricData;
     * }
     */
    public static int cBiometricData$get(MemorySegment seg) {
        return (int)constants$2065.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD cBiometricData;
     * }
     */
    public static void cBiometricData$set(MemorySegment seg, int x) {
        constants$2065.const$0.set(seg, x);
    }
    public static int cBiometricData$get(MemorySegment seg, long index) {
        return (int)constants$2065.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void cBiometricData$set(MemorySegment seg, long index, int x) {
        constants$2065.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle rgBiometricData$VH() {
        return constants$2065.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PCERT_BIOMETRIC_DATA rgBiometricData;
     * }
     */
    public static MemorySegment rgBiometricData$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$2065.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PCERT_BIOMETRIC_DATA rgBiometricData;
     * }
     */
    public static void rgBiometricData$set(MemorySegment seg, MemorySegment x) {
        constants$2065.const$1.set(seg, x);
    }
    public static MemorySegment rgBiometricData$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$2065.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void rgBiometricData$set(MemorySegment seg, long index, MemorySegment x) {
        constants$2065.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


