// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _CSV_QUERY_VETO_FILE_DIRECT_IO_OUTPUT {
 *     DWORDLONG VetoedFromAltitudeIntegral;
 *     DWORDLONG VetoedFromAltitudeDecimal;
 *     WCHAR Reason[256];
 * };
 * }
 */
public class _CSV_QUERY_VETO_FILE_DIRECT_IO_OUTPUT {

    public static MemoryLayout $LAYOUT() {
        return constants$2687.const$2;
    }
    public static VarHandle VetoedFromAltitudeIntegral$VH() {
        return constants$2687.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORDLONG VetoedFromAltitudeIntegral;
     * }
     */
    public static long VetoedFromAltitudeIntegral$get(MemorySegment seg) {
        return (long)constants$2687.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORDLONG VetoedFromAltitudeIntegral;
     * }
     */
    public static void VetoedFromAltitudeIntegral$set(MemorySegment seg, long x) {
        constants$2687.const$3.set(seg, x);
    }
    public static long VetoedFromAltitudeIntegral$get(MemorySegment seg, long index) {
        return (long)constants$2687.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void VetoedFromAltitudeIntegral$set(MemorySegment seg, long index, long x) {
        constants$2687.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle VetoedFromAltitudeDecimal$VH() {
        return constants$2687.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORDLONG VetoedFromAltitudeDecimal;
     * }
     */
    public static long VetoedFromAltitudeDecimal$get(MemorySegment seg) {
        return (long)constants$2687.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORDLONG VetoedFromAltitudeDecimal;
     * }
     */
    public static void VetoedFromAltitudeDecimal$set(MemorySegment seg, long x) {
        constants$2687.const$4.set(seg, x);
    }
    public static long VetoedFromAltitudeDecimal$get(MemorySegment seg, long index) {
        return (long)constants$2687.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void VetoedFromAltitudeDecimal$set(MemorySegment seg, long index, long x) {
        constants$2687.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment Reason$slice(MemorySegment seg) {
        return seg.asSlice(16, 512);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


