// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _DISK_GEOMETRY {
 *     LARGE_INTEGER Cylinders;
 *     MEDIA_TYPE MediaType;
 *     DWORD TracksPerCylinder;
 *     DWORD SectorsPerTrack;
 *     DWORD BytesPerSector;
 * };
 * }
 */
public class _DISK_GEOMETRY {

    public static MemoryLayout $LAYOUT() {
        return constants$2534.const$1;
    }
    public static MemorySegment Cylinders$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static VarHandle MediaType$VH() {
        return constants$2534.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * MEDIA_TYPE MediaType;
     * }
     */
    public static int MediaType$get(MemorySegment seg) {
        return (int)constants$2534.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * MEDIA_TYPE MediaType;
     * }
     */
    public static void MediaType$set(MemorySegment seg, int x) {
        constants$2534.const$2.set(seg, x);
    }
    public static int MediaType$get(MemorySegment seg, long index) {
        return (int)constants$2534.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void MediaType$set(MemorySegment seg, long index, int x) {
        constants$2534.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle TracksPerCylinder$VH() {
        return constants$2534.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD TracksPerCylinder;
     * }
     */
    public static int TracksPerCylinder$get(MemorySegment seg) {
        return (int)constants$2534.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD TracksPerCylinder;
     * }
     */
    public static void TracksPerCylinder$set(MemorySegment seg, int x) {
        constants$2534.const$3.set(seg, x);
    }
    public static int TracksPerCylinder$get(MemorySegment seg, long index) {
        return (int)constants$2534.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void TracksPerCylinder$set(MemorySegment seg, long index, int x) {
        constants$2534.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle SectorsPerTrack$VH() {
        return constants$2534.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD SectorsPerTrack;
     * }
     */
    public static int SectorsPerTrack$get(MemorySegment seg) {
        return (int)constants$2534.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD SectorsPerTrack;
     * }
     */
    public static void SectorsPerTrack$set(MemorySegment seg, int x) {
        constants$2534.const$4.set(seg, x);
    }
    public static int SectorsPerTrack$get(MemorySegment seg, long index) {
        return (int)constants$2534.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void SectorsPerTrack$set(MemorySegment seg, long index, int x) {
        constants$2534.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle BytesPerSector$VH() {
        return constants$2534.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD BytesPerSector;
     * }
     */
    public static int BytesPerSector$get(MemorySegment seg) {
        return (int)constants$2534.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD BytesPerSector;
     * }
     */
    public static void BytesPerSector$set(MemorySegment seg, int x) {
        constants$2534.const$5.set(seg, x);
    }
    public static int BytesPerSector$get(MemorySegment seg, long index) {
        return (int)constants$2534.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void BytesPerSector$set(MemorySegment seg, long index, int x) {
        constants$2534.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


