// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _NDR_USER_MARSHAL_INFO {
 *     unsigned long InformationLevel;
 *     union {
 *         NDR_USER_MARSHAL_INFO_LEVEL1 Level1;
 *     };
 * };
 * }
 */
public class _NDR_USER_MARSHAL_INFO {

    public static MemoryLayout $LAYOUT() {
        return constants$2335.const$1;
    }
    public static VarHandle InformationLevel$VH() {
        return constants$2335.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned long InformationLevel;
     * }
     */
    public static int InformationLevel$get(MemorySegment seg) {
        return (int)constants$2335.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned long InformationLevel;
     * }
     */
    public static void InformationLevel$set(MemorySegment seg, int x) {
        constants$2335.const$2.set(seg, x);
    }
    public static int InformationLevel$get(MemorySegment seg, long index) {
        return (int)constants$2335.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void InformationLevel$set(MemorySegment seg, long index, int x) {
        constants$2335.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment Level1$slice(MemorySegment seg) {
        return seg.asSlice(8, 80);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


