// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _SCM_PD_DEVICE_INFO {
 *     DWORD Version;
 *     DWORD Size;
 *     GUID DeviceGuid;
 *     DWORD UnsafeShutdownCount;
 *     DWORD64 PersistentMemorySizeInBytes;
 *     DWORD64 VolatileMemorySizeInBytes;
 *     DWORD64 TotalMemorySizeInBytes;
 *     DWORD SlotNumber;
 *     DWORD DeviceHandle;
 *     WORD PhysicalId;
 *     BYTE NumberOfFormatInterfaceCodes;
 *     WORD FormatInterfaceCodes[8];
 *     DWORD VendorId;
 *     DWORD ProductId;
 *     DWORD SubsystemDeviceId;
 *     DWORD SubsystemVendorId;
 *     BYTE ManufacturingLocation;
 *     BYTE ManufacturingWeek;
 *     BYTE ManufacturingYear;
 *     DWORD SerialNumber4Byte;
 *     DWORD SerialNumberLengthInChars;
 *     CHAR SerialNumber[1];
 * };
 * }
 */
public class _SCM_PD_DEVICE_INFO {

    public static MemoryLayout $LAYOUT() {
        return constants$2517.const$1;
    }
    public static VarHandle Version$VH() {
        return constants$2517.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD Version;
     * }
     */
    public static int Version$get(MemorySegment seg) {
        return (int)constants$2517.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD Version;
     * }
     */
    public static void Version$set(MemorySegment seg, int x) {
        constants$2517.const$2.set(seg, x);
    }
    public static int Version$get(MemorySegment seg, long index) {
        return (int)constants$2517.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void Version$set(MemorySegment seg, long index, int x) {
        constants$2517.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle Size$VH() {
        return constants$2517.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD Size;
     * }
     */
    public static int Size$get(MemorySegment seg) {
        return (int)constants$2517.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD Size;
     * }
     */
    public static void Size$set(MemorySegment seg, int x) {
        constants$2517.const$3.set(seg, x);
    }
    public static int Size$get(MemorySegment seg, long index) {
        return (int)constants$2517.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void Size$set(MemorySegment seg, long index, int x) {
        constants$2517.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment DeviceGuid$slice(MemorySegment seg) {
        return seg.asSlice(8, 16);
    }
    public static VarHandle UnsafeShutdownCount$VH() {
        return constants$2517.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD UnsafeShutdownCount;
     * }
     */
    public static int UnsafeShutdownCount$get(MemorySegment seg) {
        return (int)constants$2517.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD UnsafeShutdownCount;
     * }
     */
    public static void UnsafeShutdownCount$set(MemorySegment seg, int x) {
        constants$2517.const$4.set(seg, x);
    }
    public static int UnsafeShutdownCount$get(MemorySegment seg, long index) {
        return (int)constants$2517.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void UnsafeShutdownCount$set(MemorySegment seg, long index, int x) {
        constants$2517.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle PersistentMemorySizeInBytes$VH() {
        return constants$2517.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD64 PersistentMemorySizeInBytes;
     * }
     */
    public static long PersistentMemorySizeInBytes$get(MemorySegment seg) {
        return (long)constants$2517.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD64 PersistentMemorySizeInBytes;
     * }
     */
    public static void PersistentMemorySizeInBytes$set(MemorySegment seg, long x) {
        constants$2517.const$5.set(seg, x);
    }
    public static long PersistentMemorySizeInBytes$get(MemorySegment seg, long index) {
        return (long)constants$2517.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void PersistentMemorySizeInBytes$set(MemorySegment seg, long index, long x) {
        constants$2517.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle VolatileMemorySizeInBytes$VH() {
        return constants$2518.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD64 VolatileMemorySizeInBytes;
     * }
     */
    public static long VolatileMemorySizeInBytes$get(MemorySegment seg) {
        return (long)constants$2518.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD64 VolatileMemorySizeInBytes;
     * }
     */
    public static void VolatileMemorySizeInBytes$set(MemorySegment seg, long x) {
        constants$2518.const$0.set(seg, x);
    }
    public static long VolatileMemorySizeInBytes$get(MemorySegment seg, long index) {
        return (long)constants$2518.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void VolatileMemorySizeInBytes$set(MemorySegment seg, long index, long x) {
        constants$2518.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle TotalMemorySizeInBytes$VH() {
        return constants$2518.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD64 TotalMemorySizeInBytes;
     * }
     */
    public static long TotalMemorySizeInBytes$get(MemorySegment seg) {
        return (long)constants$2518.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD64 TotalMemorySizeInBytes;
     * }
     */
    public static void TotalMemorySizeInBytes$set(MemorySegment seg, long x) {
        constants$2518.const$1.set(seg, x);
    }
    public static long TotalMemorySizeInBytes$get(MemorySegment seg, long index) {
        return (long)constants$2518.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void TotalMemorySizeInBytes$set(MemorySegment seg, long index, long x) {
        constants$2518.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle SlotNumber$VH() {
        return constants$2518.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD SlotNumber;
     * }
     */
    public static int SlotNumber$get(MemorySegment seg) {
        return (int)constants$2518.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD SlotNumber;
     * }
     */
    public static void SlotNumber$set(MemorySegment seg, int x) {
        constants$2518.const$2.set(seg, x);
    }
    public static int SlotNumber$get(MemorySegment seg, long index) {
        return (int)constants$2518.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void SlotNumber$set(MemorySegment seg, long index, int x) {
        constants$2518.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle DeviceHandle$VH() {
        return constants$2518.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD DeviceHandle;
     * }
     */
    public static int DeviceHandle$get(MemorySegment seg) {
        return (int)constants$2518.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD DeviceHandle;
     * }
     */
    public static void DeviceHandle$set(MemorySegment seg, int x) {
        constants$2518.const$3.set(seg, x);
    }
    public static int DeviceHandle$get(MemorySegment seg, long index) {
        return (int)constants$2518.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void DeviceHandle$set(MemorySegment seg, long index, int x) {
        constants$2518.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle PhysicalId$VH() {
        return constants$2518.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * WORD PhysicalId;
     * }
     */
    public static short PhysicalId$get(MemorySegment seg) {
        return (short)constants$2518.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * WORD PhysicalId;
     * }
     */
    public static void PhysicalId$set(MemorySegment seg, short x) {
        constants$2518.const$4.set(seg, x);
    }
    public static short PhysicalId$get(MemorySegment seg, long index) {
        return (short)constants$2518.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void PhysicalId$set(MemorySegment seg, long index, short x) {
        constants$2518.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle NumberOfFormatInterfaceCodes$VH() {
        return constants$2518.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BYTE NumberOfFormatInterfaceCodes;
     * }
     */
    public static byte NumberOfFormatInterfaceCodes$get(MemorySegment seg) {
        return (byte)constants$2518.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BYTE NumberOfFormatInterfaceCodes;
     * }
     */
    public static void NumberOfFormatInterfaceCodes$set(MemorySegment seg, byte x) {
        constants$2518.const$5.set(seg, x);
    }
    public static byte NumberOfFormatInterfaceCodes$get(MemorySegment seg, long index) {
        return (byte)constants$2518.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void NumberOfFormatInterfaceCodes$set(MemorySegment seg, long index, byte x) {
        constants$2518.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment FormatInterfaceCodes$slice(MemorySegment seg) {
        return seg.asSlice(68, 16);
    }
    public static VarHandle VendorId$VH() {
        return constants$2519.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD VendorId;
     * }
     */
    public static int VendorId$get(MemorySegment seg) {
        return (int)constants$2519.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD VendorId;
     * }
     */
    public static void VendorId$set(MemorySegment seg, int x) {
        constants$2519.const$0.set(seg, x);
    }
    public static int VendorId$get(MemorySegment seg, long index) {
        return (int)constants$2519.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void VendorId$set(MemorySegment seg, long index, int x) {
        constants$2519.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ProductId$VH() {
        return constants$2519.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD ProductId;
     * }
     */
    public static int ProductId$get(MemorySegment seg) {
        return (int)constants$2519.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD ProductId;
     * }
     */
    public static void ProductId$set(MemorySegment seg, int x) {
        constants$2519.const$1.set(seg, x);
    }
    public static int ProductId$get(MemorySegment seg, long index) {
        return (int)constants$2519.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void ProductId$set(MemorySegment seg, long index, int x) {
        constants$2519.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle SubsystemDeviceId$VH() {
        return constants$2519.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD SubsystemDeviceId;
     * }
     */
    public static int SubsystemDeviceId$get(MemorySegment seg) {
        return (int)constants$2519.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD SubsystemDeviceId;
     * }
     */
    public static void SubsystemDeviceId$set(MemorySegment seg, int x) {
        constants$2519.const$2.set(seg, x);
    }
    public static int SubsystemDeviceId$get(MemorySegment seg, long index) {
        return (int)constants$2519.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void SubsystemDeviceId$set(MemorySegment seg, long index, int x) {
        constants$2519.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle SubsystemVendorId$VH() {
        return constants$2519.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD SubsystemVendorId;
     * }
     */
    public static int SubsystemVendorId$get(MemorySegment seg) {
        return (int)constants$2519.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD SubsystemVendorId;
     * }
     */
    public static void SubsystemVendorId$set(MemorySegment seg, int x) {
        constants$2519.const$3.set(seg, x);
    }
    public static int SubsystemVendorId$get(MemorySegment seg, long index) {
        return (int)constants$2519.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void SubsystemVendorId$set(MemorySegment seg, long index, int x) {
        constants$2519.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ManufacturingLocation$VH() {
        return constants$2519.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BYTE ManufacturingLocation;
     * }
     */
    public static byte ManufacturingLocation$get(MemorySegment seg) {
        return (byte)constants$2519.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BYTE ManufacturingLocation;
     * }
     */
    public static void ManufacturingLocation$set(MemorySegment seg, byte x) {
        constants$2519.const$4.set(seg, x);
    }
    public static byte ManufacturingLocation$get(MemorySegment seg, long index) {
        return (byte)constants$2519.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void ManufacturingLocation$set(MemorySegment seg, long index, byte x) {
        constants$2519.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ManufacturingWeek$VH() {
        return constants$2519.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BYTE ManufacturingWeek;
     * }
     */
    public static byte ManufacturingWeek$get(MemorySegment seg) {
        return (byte)constants$2519.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BYTE ManufacturingWeek;
     * }
     */
    public static void ManufacturingWeek$set(MemorySegment seg, byte x) {
        constants$2519.const$5.set(seg, x);
    }
    public static byte ManufacturingWeek$get(MemorySegment seg, long index) {
        return (byte)constants$2519.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void ManufacturingWeek$set(MemorySegment seg, long index, byte x) {
        constants$2519.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ManufacturingYear$VH() {
        return constants$2520.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * BYTE ManufacturingYear;
     * }
     */
    public static byte ManufacturingYear$get(MemorySegment seg) {
        return (byte)constants$2520.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * BYTE ManufacturingYear;
     * }
     */
    public static void ManufacturingYear$set(MemorySegment seg, byte x) {
        constants$2520.const$0.set(seg, x);
    }
    public static byte ManufacturingYear$get(MemorySegment seg, long index) {
        return (byte)constants$2520.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void ManufacturingYear$set(MemorySegment seg, long index, byte x) {
        constants$2520.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle SerialNumber4Byte$VH() {
        return constants$2520.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD SerialNumber4Byte;
     * }
     */
    public static int SerialNumber4Byte$get(MemorySegment seg) {
        return (int)constants$2520.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD SerialNumber4Byte;
     * }
     */
    public static void SerialNumber4Byte$set(MemorySegment seg, int x) {
        constants$2520.const$1.set(seg, x);
    }
    public static int SerialNumber4Byte$get(MemorySegment seg, long index) {
        return (int)constants$2520.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void SerialNumber4Byte$set(MemorySegment seg, long index, int x) {
        constants$2520.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle SerialNumberLengthInChars$VH() {
        return constants$2520.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD SerialNumberLengthInChars;
     * }
     */
    public static int SerialNumberLengthInChars$get(MemorySegment seg) {
        return (int)constants$2520.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD SerialNumberLengthInChars;
     * }
     */
    public static void SerialNumberLengthInChars$set(MemorySegment seg, int x) {
        constants$2520.const$2.set(seg, x);
    }
    public static int SerialNumberLengthInChars$get(MemorySegment seg, long index) {
        return (int)constants$2520.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void SerialNumberLengthInChars$set(MemorySegment seg, long index, int x) {
        constants$2520.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment SerialNumber$slice(MemorySegment seg) {
        return seg.asSlice(112, 1);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


