// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct _TOKEN_ACCESS_INFORMATION {
 *     PSID_AND_ATTRIBUTES_HASH SidHash;
 *     PSID_AND_ATTRIBUTES_HASH RestrictedSidHash;
 *     PTOKEN_PRIVILEGES Privileges;
 *     LUID AuthenticationId;
 *     TOKEN_TYPE TokenType;
 *     SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
 *     TOKEN_MANDATORY_POLICY MandatoryPolicy;
 *     DWORD Flags;
 *     DWORD AppContainerNumber;
 *     PSID PackageSid;
 *     PSID_AND_ATTRIBUTES_HASH CapabilitiesHash;
 *     PSID TrustLevelSid;
 *     PSECURITY_ATTRIBUTES_OPAQUE SecurityAttributes;
 * };
 * }
 */
public class _TOKEN_ACCESS_INFORMATION {

    public static MemoryLayout $LAYOUT() {
        return constants$170.const$1;
    }
    public static VarHandle SidHash$VH() {
        return constants$170.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PSID_AND_ATTRIBUTES_HASH SidHash;
     * }
     */
    public static MemorySegment SidHash$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$170.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PSID_AND_ATTRIBUTES_HASH SidHash;
     * }
     */
    public static void SidHash$set(MemorySegment seg, MemorySegment x) {
        constants$170.const$2.set(seg, x);
    }
    public static MemorySegment SidHash$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$170.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void SidHash$set(MemorySegment seg, long index, MemorySegment x) {
        constants$170.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle RestrictedSidHash$VH() {
        return constants$170.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PSID_AND_ATTRIBUTES_HASH RestrictedSidHash;
     * }
     */
    public static MemorySegment RestrictedSidHash$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$170.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PSID_AND_ATTRIBUTES_HASH RestrictedSidHash;
     * }
     */
    public static void RestrictedSidHash$set(MemorySegment seg, MemorySegment x) {
        constants$170.const$3.set(seg, x);
    }
    public static MemorySegment RestrictedSidHash$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$170.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void RestrictedSidHash$set(MemorySegment seg, long index, MemorySegment x) {
        constants$170.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle Privileges$VH() {
        return constants$170.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PTOKEN_PRIVILEGES Privileges;
     * }
     */
    public static MemorySegment Privileges$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$170.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PTOKEN_PRIVILEGES Privileges;
     * }
     */
    public static void Privileges$set(MemorySegment seg, MemorySegment x) {
        constants$170.const$4.set(seg, x);
    }
    public static MemorySegment Privileges$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$170.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void Privileges$set(MemorySegment seg, long index, MemorySegment x) {
        constants$170.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment AuthenticationId$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static VarHandle TokenType$VH() {
        return constants$170.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * TOKEN_TYPE TokenType;
     * }
     */
    public static int TokenType$get(MemorySegment seg) {
        return (int)constants$170.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * TOKEN_TYPE TokenType;
     * }
     */
    public static void TokenType$set(MemorySegment seg, int x) {
        constants$170.const$5.set(seg, x);
    }
    public static int TokenType$get(MemorySegment seg, long index) {
        return (int)constants$170.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void TokenType$set(MemorySegment seg, long index, int x) {
        constants$170.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ImpersonationLevel$VH() {
        return constants$171.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
     * }
     */
    public static int ImpersonationLevel$get(MemorySegment seg) {
        return (int)constants$171.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
     * }
     */
    public static void ImpersonationLevel$set(MemorySegment seg, int x) {
        constants$171.const$0.set(seg, x);
    }
    public static int ImpersonationLevel$get(MemorySegment seg, long index) {
        return (int)constants$171.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void ImpersonationLevel$set(MemorySegment seg, long index, int x) {
        constants$171.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment MandatoryPolicy$slice(MemorySegment seg) {
        return seg.asSlice(40, 4);
    }
    public static VarHandle Flags$VH() {
        return constants$171.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD Flags;
     * }
     */
    public static int Flags$get(MemorySegment seg) {
        return (int)constants$171.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD Flags;
     * }
     */
    public static void Flags$set(MemorySegment seg, int x) {
        constants$171.const$1.set(seg, x);
    }
    public static int Flags$get(MemorySegment seg, long index) {
        return (int)constants$171.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void Flags$set(MemorySegment seg, long index, int x) {
        constants$171.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle AppContainerNumber$VH() {
        return constants$171.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * DWORD AppContainerNumber;
     * }
     */
    public static int AppContainerNumber$get(MemorySegment seg) {
        return (int)constants$171.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * DWORD AppContainerNumber;
     * }
     */
    public static void AppContainerNumber$set(MemorySegment seg, int x) {
        constants$171.const$2.set(seg, x);
    }
    public static int AppContainerNumber$get(MemorySegment seg, long index) {
        return (int)constants$171.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void AppContainerNumber$set(MemorySegment seg, long index, int x) {
        constants$171.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle PackageSid$VH() {
        return constants$171.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PSID PackageSid;
     * }
     */
    public static MemorySegment PackageSid$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$171.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PSID PackageSid;
     * }
     */
    public static void PackageSid$set(MemorySegment seg, MemorySegment x) {
        constants$171.const$3.set(seg, x);
    }
    public static MemorySegment PackageSid$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$171.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void PackageSid$set(MemorySegment seg, long index, MemorySegment x) {
        constants$171.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle CapabilitiesHash$VH() {
        return constants$171.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PSID_AND_ATTRIBUTES_HASH CapabilitiesHash;
     * }
     */
    public static MemorySegment CapabilitiesHash$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$171.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PSID_AND_ATTRIBUTES_HASH CapabilitiesHash;
     * }
     */
    public static void CapabilitiesHash$set(MemorySegment seg, MemorySegment x) {
        constants$171.const$4.set(seg, x);
    }
    public static MemorySegment CapabilitiesHash$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$171.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void CapabilitiesHash$set(MemorySegment seg, long index, MemorySegment x) {
        constants$171.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle TrustLevelSid$VH() {
        return constants$171.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PSID TrustLevelSid;
     * }
     */
    public static MemorySegment TrustLevelSid$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$171.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PSID TrustLevelSid;
     * }
     */
    public static void TrustLevelSid$set(MemorySegment seg, MemorySegment x) {
        constants$171.const$5.set(seg, x);
    }
    public static MemorySegment TrustLevelSid$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$171.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void TrustLevelSid$set(MemorySegment seg, long index, MemorySegment x) {
        constants$171.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle SecurityAttributes$VH() {
        return constants$172.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PSECURITY_ATTRIBUTES_OPAQUE SecurityAttributes;
     * }
     */
    public static MemorySegment SecurityAttributes$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$172.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PSECURITY_ATTRIBUTES_OPAQUE SecurityAttributes;
     * }
     */
    public static void SecurityAttributes$set(MemorySegment seg, MemorySegment x) {
        constants$172.const$0.set(seg, x);
    }
    public static MemorySegment SecurityAttributes$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$172.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void SecurityAttributes$set(MemorySegment seg, long index, MemorySegment x) {
        constants$172.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


