// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct tagBIND_OPTS3 BIND_OPTS3;
 * }
 */
public final class BIND_OPTS3 extends tagBIND_OPTS3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private BIND_OPTS3() {}
}


