// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _CERT_OTHER_NAME {
 *     LPSTR pszObjId;
 *     CRYPT_OBJID_BLOB Value;
 * } CERT_OTHER_NAME
 * }
 */
public class CERT_OTHER_NAME extends _CERT_OTHER_NAME {

    CERT_OTHER_NAME() {
        // Should not be called directly
    }
}

