// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _CHANGER_SEND_VOLUME_TAG_INFORMATION CHANGER_SEND_VOLUME_TAG_INFORMATION;
 * }
 */
public final class CHANGER_SEND_VOLUME_TAG_INFORMATION extends _CHANGER_SEND_VOLUME_TAG_INFORMATION {

    // Suppresses default constructor, ensuring non-instantiability.
    private CHANGER_SEND_VOLUME_TAG_INFORMATION() {}
}


