// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _CMSG_ENVELOPED_ENCODE_INFO {
 *     DWORD cbSize;
 *     HCRYPTPROV_LEGACY hCryptProv;
 *     CRYPT_ALGORITHM_IDENTIFIER ContentEncryptionAlgorithm;
 *     void *pvEncryptionAuxInfo;
 *     DWORD cRecipients;
 *     PCERT_INFO *rgpRecipients;
 * } CMSG_ENVELOPED_ENCODE_INFO
 * }
 */
public class CMSG_ENVELOPED_ENCODE_INFO extends _CMSG_ENVELOPED_ENCODE_INFO {

    CMSG_ENVELOPED_ENCODE_INFO() {
        // Should not be called directly
    }
}

