// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4479 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4479() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("lpDescription")
    ).withName("_SERVICE_DESCRIPTIONW");
    static final VarHandle const$1 = constants$4479.const$0.varHandle(MemoryLayout.PathElement.groupElement("lpDescription"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("Type"),
        JAVA_INT.withName("Delay")
    ).withName("_SC_ACTION");
    static final VarHandle const$3 = constants$4479.const$2.varHandle(MemoryLayout.PathElement.groupElement("Type"));
    static final VarHandle const$4 = constants$4479.const$2.varHandle(MemoryLayout.PathElement.groupElement("Delay"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("dwResetPeriod"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("lpRebootMsg"),
        RuntimeHelper.POINTER.withName("lpCommand"),
        JAVA_INT.withName("cActions"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("lpsaActions")
    ).withName("_SERVICE_FAILURE_ACTIONSA");
}


