// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1813 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1813() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "RpcNsGroupMbrAddW",
        constants$1425.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "RpcNsGroupMbrRemoveW",
        constants$1425.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "RpcNsGroupMbrInqBeginW",
        constants$1425.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "RpcNsGroupMbrInqNextW",
        constants$34.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "RpcNsGroupMbrInqDone",
        constants$18.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "RpcNsProfileDeleteA",
        constants$12.const$0
    );
}


