// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4299 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4299() {}
    static final VarHandle const$0 = constants$4298.const$5.varHandle(MemoryLayout.PathElement.groupElement("cbSize"));
    static final VarHandle const$1 = constants$4298.const$5.varHandle(MemoryLayout.PathElement.groupElement("dwFlags"));
    static final VarHandle const$2 = constants$4298.const$5.varHandle(MemoryLayout.PathElement.groupElement("dwAdState"));
    static final VarHandle const$3 = constants$4298.const$5.varHandle(MemoryLayout.PathElement.groupElement("szTitle"));
    static final VarHandle const$4 = constants$4298.const$5.varHandle(MemoryLayout.PathElement.groupElement("szAbstract"));
    static final VarHandle const$5 = constants$4298.const$5.varHandle(MemoryLayout.PathElement.groupElement("szHREF"));
}


