// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1166 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1166() {}
    static final VarHandle const$0 = constants$1165.const$1.varHandle(MemoryLayout.PathElement.groupElement("time"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("ptReserved"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("ptMaxSize"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("ptMaxPosition"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("ptMinTrackSize"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("ptMaxTrackSize")
    ).withName("tagMINMAXINFO");
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_LONG.withName("dwData"),
        JAVA_INT.withName("cbData"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("lpData")
    ).withName("tagCOPYDATASTRUCT");
    static final VarHandle const$3 = constants$1166.const$2.varHandle(MemoryLayout.PathElement.groupElement("dwData"));
    static final VarHandle const$4 = constants$1166.const$2.varHandle(MemoryLayout.PathElement.groupElement("cbData"));
    static final VarHandle const$5 = constants$1166.const$2.varHandle(MemoryLayout.PathElement.groupElement("lpData"));
}


