// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$539 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$539() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("unused")
    ).withName("HTASK__");
    static final VarHandle const$1 = constants$539.const$0.varHandle(MemoryLayout.PathElement.groupElement("unused"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("unused")
    ).withName("HWINSTA__");
    static final VarHandle const$3 = constants$539.const$2.varHandle(MemoryLayout.PathElement.groupElement("unused"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("unused")
    ).withName("HKL__");
    static final VarHandle const$5 = constants$539.const$4.varHandle(MemoryLayout.PathElement.groupElement("unused"));
}


