// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1770 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1770() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "RpcMgmtEpEltInqDone",
        constants$18.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "RpcMgmtEpEltInqNextA",
        constants$577.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "RpcMgmtEpEltInqNextW",
        constants$577.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "RpcMgmtEpUnregister",
        constants$1.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(RPC_MGMT_AUTHORIZATION_FN.class, "apply", constants$485.const$5);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$485.const$5
    );
}


