// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "__pwctype_func",
        constants$2.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_SHORT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "iswalnum",
        constants$5.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "iswalpha",
        constants$5.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "iswascii",
        constants$5.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "iswblank",
        constants$5.const$1
    );
}


