// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3829 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3829() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(IXMLDOMCharacterDataVtbl.put_dataType.class, "apply", constants$34.const$0);
    static final VarHandle const$1 = constants$3817.const$5.varHandle(MemoryLayout.PathElement.groupElement("put_dataType"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(IXMLDOMCharacterDataVtbl.get_xml.class, "apply", constants$34.const$0);
    static final VarHandle const$3 = constants$3817.const$5.varHandle(MemoryLayout.PathElement.groupElement("get_xml"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(IXMLDOMCharacterDataVtbl.transformNode.class, "apply", constants$37.const$3);
    static final VarHandle const$5 = constants$3817.const$5.varHandle(MemoryLayout.PathElement.groupElement("transformNode"));
}


