// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1453 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1453() {}
    static final VarHandle const$0 = constants$1452.const$3.varHandle(MemoryLayout.PathElement.groupElement("Attributes"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("nFont"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("X"),
            JAVA_SHORT.withName("Y")
        ).withName("dwFontSize")
    ).withName("_CONSOLE_FONT_INFO");
    static final VarHandle const$2 = constants$1453.const$1.varHandle(MemoryLayout.PathElement.groupElement("nFont"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "AllocConsole",
        constants$1.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "FreeConsole",
        constants$1.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "AttachConsole",
        constants$11.const$5
    );
}


