// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4442 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4442() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("lStructSize"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("hwndOwner"),
        RuntimeHelper.POINTER.withName("hDC"),
        RuntimeHelper.POINTER.withName("lpLogFont"),
        JAVA_INT.withName("iPointSize"),
        JAVA_INT.withName("Flags"),
        JAVA_INT.withName("rgbColors"),
        MemoryLayout.paddingLayout(4),
        JAVA_LONG.withName("lCustData"),
        RuntimeHelper.POINTER.withName("lpfnHook"),
        RuntimeHelper.POINTER.withName("lpTemplateName"),
        RuntimeHelper.POINTER.withName("hInstance"),
        RuntimeHelper.POINTER.withName("lpszStyle"),
        JAVA_SHORT.withName("nFontType"),
        JAVA_SHORT.withName("___MISSING_ALIGNMENT__"),
        JAVA_INT.withName("nSizeMin"),
        JAVA_INT.withName("nSizeMax"),
        MemoryLayout.paddingLayout(4)
    ).withName("tagCHOOSEFONTA");
    static final VarHandle const$1 = constants$4442.const$0.varHandle(MemoryLayout.PathElement.groupElement("lStructSize"));
    static final VarHandle const$2 = constants$4442.const$0.varHandle(MemoryLayout.PathElement.groupElement("hwndOwner"));
    static final VarHandle const$3 = constants$4442.const$0.varHandle(MemoryLayout.PathElement.groupElement("hDC"));
    static final VarHandle const$4 = constants$4442.const$0.varHandle(MemoryLayout.PathElement.groupElement("lpLogFont"));
    static final VarHandle const$5 = constants$4442.const$0.varHandle(MemoryLayout.PathElement.groupElement("iPointSize"));
}


