// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2154 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2154() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "CryptMsgEncodeAndSignCTL",
        constants$735.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "CertFindSubjectInSortedCTL",
        constants$588.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "CertEnumSubjectInSortedCTL",
        constants$1.const$3
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("cbSize"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.structLayout(
            JAVA_INT.withName("cbData"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("pbData")
        ).withName("ListIdentifier"),
        JAVA_INT.withName("cCtlStore"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("rghCtlStore"),
        JAVA_INT.withName("cSignerStore"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("rghSignerStore")
    ).withName("_CTL_VERIFY_USAGE_PARA");
    static final VarHandle const$4 = constants$2154.const$3.varHandle(MemoryLayout.PathElement.groupElement("cbSize"));
    static final VarHandle const$5 = constants$2154.const$3.varHandle(MemoryLayout.PathElement.groupElement("cCtlStore"));
}


