// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3582 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3582() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ITypeLib_FindName_Proxy",
        constants$608.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ITypeLib_FindName_Stub",
        constants$2185.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ITypeLib_ReleaseTLibAttr_Proxy",
        constants$469.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ITypeLib_ReleaseTLibAttr_Stub",
        constants$18.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ITypeLib2_GetLibStatistics_Proxy",
        constants$37.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ITypeLib2_GetLibStatistics_Stub",
        constants$37.const$3
    );
}


