// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1201 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1201() {}
    static final VarHandle const$0 = constants$1199.const$2.varHandle(MemoryLayout.PathElement.groupElement("prcDirty"));
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "UpdateLayeredWindowIndirect",
        constants$34.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "GetLayeredWindowAttributes",
        constants$1.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "PrintWindow",
        constants$570.const$5
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_BYTE,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SetLayeredWindowAttributes",
        constants$1201.const$4
    );
}


