// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2640 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2640() {}
    static final VarHandle const$0 = constants$2639.const$3.varHandle(MemoryLayout.PathElement.groupElement("BytesWithinFileSize"));
    static final VarHandle const$1 = constants$2639.const$3.varHandle(MemoryLayout.PathElement.groupElement("BytesWithinValidDataLength"));
    static final VarHandle const$2 = constants$2639.const$3.varHandle(MemoryLayout.PathElement.groupElement("CompressionFormat"));
    static final VarHandle const$3 = constants$2639.const$3.varHandle(MemoryLayout.PathElement.groupElement("DataUnitShift"));
    static final VarHandle const$4 = constants$2639.const$3.varHandle(MemoryLayout.PathElement.groupElement("ChunkShift"));
    static final VarHandle const$5 = constants$2639.const$3.varHandle(MemoryLayout.PathElement.groupElement("ClusterShift"));
}


