// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$547 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$547() {}
    static final VarHandle const$0 = constants$546.const$3.varHandle(MemoryLayout.PathElement.groupElement("right"));
    static final VarHandle const$1 = constants$546.const$3.varHandle(MemoryLayout.PathElement.groupElement("bottom"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("left"),
        JAVA_INT.withName("top"),
        JAVA_INT.withName("right"),
        JAVA_INT.withName("bottom")
    ).withName("_RECTL");
    static final VarHandle const$3 = constants$547.const$2.varHandle(MemoryLayout.PathElement.groupElement("left"));
    static final VarHandle const$4 = constants$547.const$2.varHandle(MemoryLayout.PathElement.groupElement("top"));
    static final VarHandle const$5 = constants$547.const$2.varHandle(MemoryLayout.PathElement.groupElement("right"));
}


