// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2866 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2866() {}
    static final VarHandle const$0 = constants$2864.const$2.varHandle(MemoryLayout.PathElement.groupElement("pDefaultDataType"));
    static final VarHandle const$1 = constants$2864.const$2.varHandle(MemoryLayout.PathElement.groupElement("pszzPreviousNames"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("cVersion"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pName"),
        RuntimeHelper.POINTER.withName("pEnvironment"),
        RuntimeHelper.POINTER.withName("pDriverPath"),
        RuntimeHelper.POINTER.withName("pDataFile"),
        RuntimeHelper.POINTER.withName("pConfigFile"),
        RuntimeHelper.POINTER.withName("pHelpFile"),
        RuntimeHelper.POINTER.withName("pDependentFiles"),
        RuntimeHelper.POINTER.withName("pMonitorName"),
        RuntimeHelper.POINTER.withName("pDefaultDataType"),
        RuntimeHelper.POINTER.withName("pszzPreviousNames")
    ).withName("_DRIVER_INFO_4W");
    static final VarHandle const$3 = constants$2866.const$2.varHandle(MemoryLayout.PathElement.groupElement("cVersion"));
    static final VarHandle const$4 = constants$2866.const$2.varHandle(MemoryLayout.PathElement.groupElement("pName"));
    static final VarHandle const$5 = constants$2866.const$2.varHandle(MemoryLayout.PathElement.groupElement("pEnvironment"));
}


