// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1992 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1992() {}
    static final VarHandle const$0 = constants$1991.const$5.varHandle(MemoryLayout.PathElement.groupElement("dwVersion"));
    static final VarHandle const$1 = constants$1991.const$5.varHandle(MemoryLayout.PathElement.groupElement("dwFlags"));
    static final VarHandle const$2 = constants$1991.const$5.varHandle(MemoryLayout.PathElement.groupElement("pszCreationTitle"));
    static final VarHandle const$3 = constants$1991.const$5.varHandle(MemoryLayout.PathElement.groupElement("pszFriendlyName"));
    static final VarHandle const$4 = constants$1991.const$5.varHandle(MemoryLayout.PathElement.groupElement("pszDescription"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("dwVersion"),
        JAVA_INT.withName("dwPolicyFlags"),
        JAVA_INT.withName("cbUserSid"),
        JAVA_INT.withName("cbApplicationSid")
    ).withName("__NCRYPT_KEY_ACCESS_POLICY_BLOB");
}


