// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2522 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2522() {}
    static final VarHandle const$0 = constants$2521.const$3.varHandle(MemoryLayout.PathElement.groupElement("SlotNumber"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("Version"),
        JAVA_INT.withName("Size"),
        JAVA_BYTE.withName("ActiveSlot"),
        JAVA_BYTE.withName("NextActiveSlot"),
        JAVA_BYTE.withName("SlotCount"),
        MemoryLayout.paddingLayout(1),
        MemoryLayout.sequenceLayout(1, MemoryLayout.structLayout(
            JAVA_INT.withName("Version"),
            JAVA_INT.withName("Size"),
            JAVA_BYTE.withName("SlotNumber"),
            MemoryLayout.paddingLayout(1),
            MemoryLayout.sequenceLayout(6, JAVA_BYTE).withName("Reserved1"),
            MemoryLayout.sequenceLayout(32, JAVA_BYTE).withName("Revision")
        ).withName("_SCM_PD_FIRMWARE_SLOT_INFO")).withName("Slots")
    ).withName("_SCM_PD_FIRMWARE_INFO");
    static final VarHandle const$2 = constants$2522.const$1.varHandle(MemoryLayout.PathElement.groupElement("Version"));
    static final VarHandle const$3 = constants$2522.const$1.varHandle(MemoryLayout.PathElement.groupElement("Size"));
    static final VarHandle const$4 = constants$2522.const$1.varHandle(MemoryLayout.PathElement.groupElement("ActiveSlot"));
    static final VarHandle const$5 = constants$2522.const$1.varHandle(MemoryLayout.PathElement.groupElement("NextActiveSlot"));
}


