// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4304 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4304() {}
    static final VarHandle const$0 = constants$4301.const$4.varHandle(MemoryLayout.PathElement.groupElement("AsyncInstallDistributionUnit"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("lpVtbl")
    ).withName("ISoftDistExt");
    static final VarHandle const$2 = constants$4304.const$1.varHandle(MemoryLayout.PathElement.groupElement("lpVtbl"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "GetSoftwareUpdateInfo",
        constants$34.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SetSoftwareUpdateAdvertisementState",
        constants$775.const$4
    );
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_urlmon_0000_0048_v0_0_c_ifspec", RuntimeHelper.POINTER);
}


