// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4509 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4509() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "OpenServiceA",
        constants$713.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "OpenServiceW",
        constants$713.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "QueryServiceConfigA",
        constants$586.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "QueryServiceConfigW",
        constants$586.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "QueryServiceConfig2A",
        constants$703.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "QueryServiceConfig2W",
        constants$703.const$2
    );
}


