// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2274 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2274() {}
    static final VarHandle const$0 = constants$2266.const$3.varHandle(MemoryLayout.PathElement.groupElement("dwStubPhase"));
    static final VarHandle const$1 = constants$2266.const$3.varHandle(MemoryLayout.PathElement.groupElement("LowStackMark"));
    static final VarHandle const$2 = constants$2266.const$3.varHandle(MemoryLayout.PathElement.groupElement("pAsyncMsg"));
    static final VarHandle const$3 = constants$2266.const$3.varHandle(MemoryLayout.PathElement.groupElement("pCorrInfo"));
    static final VarHandle const$4 = constants$2266.const$3.varHandle(MemoryLayout.PathElement.groupElement("pCorrMemory"));
    static final VarHandle const$5 = constants$2266.const$3.varHandle(MemoryLayout.PathElement.groupElement("pMemoryList"));
}


