// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$414 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$414() {}
    static final VarHandle const$0 = constants$413.const$3.varHandle(MemoryLayout.PathElement.groupElement("MajorVersion"));
    static final VarHandle const$1 = constants$413.const$3.varHandle(MemoryLayout.PathElement.groupElement("MinorVersion"));
    static final VarHandle const$2 = constants$413.const$3.varHandle(MemoryLayout.PathElement.groupElement("NumberOfNamedEntries"));
    static final VarHandle const$3 = constants$413.const$3.varHandle(MemoryLayout.PathElement.groupElement("NumberOfIdEntries"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                MemoryLayout.paddingLayout(4)
            ).withName("$anon$0"),
            JAVA_INT.withName("Name"),
            JAVA_SHORT.withName("Id")
        ).withName("$anon$0"),
        MemoryLayout.unionLayout(
            JAVA_INT.withName("OffsetToData"),
            MemoryLayout.structLayout(
                MemoryLayout.paddingLayout(4)
            ).withName("$anon$0")
        ).withName("$anon$1")
    ).withName("_IMAGE_RESOURCE_DIRECTORY_ENTRY");
    static final VarHandle const$5 = constants$414.const$4.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("Name"));
}


