// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$236 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$236() {}
    static final VarHandle const$0 = constants$235.const$3.varHandle(MemoryLayout.PathElement.groupElement("LogicalProcessorIndex"));
    static final VarHandle const$1 = constants$235.const$3.varHandle(MemoryLayout.PathElement.groupElement("CoreIndex"));
    static final VarHandle const$2 = constants$235.const$3.varHandle(MemoryLayout.PathElement.groupElement("LastLevelCacheIndex"));
    static final VarHandle const$3 = constants$235.const$3.varHandle(MemoryLayout.PathElement.groupElement("NumaNodeIndex"));
    static final VarHandle const$4 = constants$235.const$3.varHandle(MemoryLayout.PathElement.groupElement("EfficiencyClass"));
    static final VarHandle const$5 = constants$235.const$3.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("AllFlags"));
}


