// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$874 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$874() {}
    static final VarHandle const$0 = constants$873.const$2.varHandle(MemoryLayout.PathElement.groupElement("FileSystemEffectivePhysicalBytesPerSectorForAtomicity"));
    static final VarHandle const$1 = constants$873.const$2.varHandle(MemoryLayout.PathElement.groupElement("Flags"));
    static final VarHandle const$2 = constants$873.const$2.varHandle(MemoryLayout.PathElement.groupElement("ByteOffsetForSectorAlignment"));
    static final VarHandle const$3 = constants$873.const$2.varHandle(MemoryLayout.PathElement.groupElement("ByteOffsetForPartitionAlignment"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_LONG.withName("VolumeSerialNumber"),
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(16, JAVA_BYTE).withName("Identifier")
        ).withName("FileId")
    ).withName("_FILE_ID_INFO");
    static final VarHandle const$5 = constants$874.const$4.varHandle(MemoryLayout.PathElement.groupElement("VolumeSerialNumber"));
}


