// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2121 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2121() {}
    static final VarHandle const$0 = constants$2119.const$4.varHandle(MemoryLayout.PathElement.groupElement("cbCtlContent"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("dwParam"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("pbData"),
        JAVA_INT.withName("cbData"),
        JAVA_INT.withName("dwFlags")
    ).withName("_CRYPT_KEY_PROV_PARAM");
    static final VarHandle const$2 = constants$2121.const$1.varHandle(MemoryLayout.PathElement.groupElement("dwParam"));
    static final VarHandle const$3 = constants$2121.const$1.varHandle(MemoryLayout.PathElement.groupElement("pbData"));
    static final VarHandle const$4 = constants$2121.const$1.varHandle(MemoryLayout.PathElement.groupElement("cbData"));
    static final VarHandle const$5 = constants$2121.const$1.varHandle(MemoryLayout.PathElement.groupElement("dwFlags"));
}


