// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2484 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2484() {}
    static final VarHandle const$0 = constants$2483.const$4.varHandle(MemoryLayout.PathElement.groupElement("LogSectors"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withByteAlignment(1).withName("dwFlags"),
        MemoryLayout.sequenceLayout(16, MemoryLayout.structLayout(
            JAVA_SHORT.withByteAlignment(1).withName("LogAddress"),
            JAVA_SHORT.withByteAlignment(1).withName("LogSectors")
        ).withName("_GP_LOG_PAGE_DESCRIPTOR")).withName("GPLogTable"),
        MemoryLayout.sequenceLayout(16, JAVA_BYTE).withName("szDescription"),
        MemoryLayout.sequenceLayout(1, JAVA_BYTE).withName("bData")
    ).withName("_DEVICEDUMP_PUBLIC_SUBSECTION");
    static final VarHandle const$2 = constants$2484.const$1.varHandle(MemoryLayout.PathElement.groupElement("dwFlags"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(1, JAVA_BYTE).withName("bData")
    ).withName("_DEVICEDUMP_RESTRICTED_SUBSECTION");
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withByteAlignment(1).withName("dwFlags"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withByteAlignment(1).withName("LogAddress"),
            JAVA_SHORT.withByteAlignment(1).withName("LogSectors")
        ).withName("GPLogId"),
        MemoryLayout.sequenceLayout(1, JAVA_BYTE).withName("bData")
    ).withName("_DEVICEDUMP_PRIVATE_SUBSECTION");
    static final VarHandle const$5 = constants$2484.const$4.varHandle(MemoryLayout.PathElement.groupElement("dwFlags"));
}


