// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3394 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3394() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "HDC_UserMarshal64",
        constants$33.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "HDC_UserUnmarshal64",
        constants$33.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "HDC_UserFree64",
        constants$469.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "HICON_UserSize64",
        constants$485.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "HICON_UserMarshal64",
        constants$33.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "HICON_UserUnmarshal64",
        constants$33.const$1
    );
}


