// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1993 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1993() {}
    static final VarHandle const$0 = constants$1992.const$5.varHandle(MemoryLayout.PathElement.groupElement("dwVersion"));
    static final VarHandle const$1 = constants$1992.const$5.varHandle(MemoryLayout.PathElement.groupElement("dwPolicyFlags"));
    static final VarHandle const$2 = constants$1992.const$5.varHandle(MemoryLayout.PathElement.groupElement("cbUserSid"));
    static final VarHandle const$3 = constants$1992.const$5.varHandle(MemoryLayout.PathElement.groupElement("cbApplicationSid"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("dwMinLength"),
        JAVA_INT.withName("dwMaxLength"),
        JAVA_INT.withName("dwIncrement"),
        JAVA_INT.withName("dwDefaultLength")
    ).withName("__NCRYPT_SUPPORTED_LENGTHS");
    static final VarHandle const$5 = constants$1993.const$4.varHandle(MemoryLayout.PathElement.groupElement("dwMinLength"));
}


