// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$975 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$975() {}
    static final VarHandle const$0 = constants$971.const$1.varHandle(MemoryLayout.PathElement.groupElement("otmpFaceName"));
    static final VarHandle const$1 = constants$971.const$1.varHandle(MemoryLayout.PathElement.groupElement("otmpStyleName"));
    static final VarHandle const$2 = constants$971.const$1.varHandle(MemoryLayout.PathElement.groupElement("otmpFullName"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("otmSize"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("tmHeight"),
            JAVA_INT.withName("tmAscent"),
            JAVA_INT.withName("tmDescent"),
            JAVA_INT.withName("tmInternalLeading"),
            JAVA_INT.withName("tmExternalLeading"),
            JAVA_INT.withName("tmAveCharWidth"),
            JAVA_INT.withName("tmMaxCharWidth"),
            JAVA_INT.withName("tmWeight"),
            JAVA_INT.withName("tmOverhang"),
            JAVA_INT.withName("tmDigitizedAspectX"),
            JAVA_INT.withName("tmDigitizedAspectY"),
            JAVA_SHORT.withName("tmFirstChar"),
            JAVA_SHORT.withName("tmLastChar"),
            JAVA_SHORT.withName("tmDefaultChar"),
            JAVA_SHORT.withName("tmBreakChar"),
            JAVA_BYTE.withName("tmItalic"),
            JAVA_BYTE.withName("tmUnderlined"),
            JAVA_BYTE.withName("tmStruckOut"),
            JAVA_BYTE.withName("tmPitchAndFamily"),
            JAVA_BYTE.withName("tmCharSet"),
            MemoryLayout.paddingLayout(3)
        ).withName("otmTextMetrics"),
        JAVA_BYTE.withName("otmFiller"),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("bFamilyType"),
            JAVA_BYTE.withName("bSerifStyle"),
            JAVA_BYTE.withName("bWeight"),
            JAVA_BYTE.withName("bProportion"),
            JAVA_BYTE.withName("bContrast"),
            JAVA_BYTE.withName("bStrokeVariation"),
            JAVA_BYTE.withName("bArmStyle"),
            JAVA_BYTE.withName("bLetterform"),
            JAVA_BYTE.withName("bMidline"),
            JAVA_BYTE.withName("bXHeight")
        ).withName("otmPanoseNumber"),
        MemoryLayout.paddingLayout(1),
        JAVA_INT.withName("otmfsSelection"),
        JAVA_INT.withName("otmfsType"),
        JAVA_INT.withName("otmsCharSlopeRise"),
        JAVA_INT.withName("otmsCharSlopeRun"),
        JAVA_INT.withName("otmItalicAngle"),
        JAVA_INT.withName("otmEMSquare"),
        JAVA_INT.withName("otmAscent"),
        JAVA_INT.withName("otmDescent"),
        JAVA_INT.withName("otmLineGap"),
        JAVA_INT.withName("otmsCapEmHeight"),
        JAVA_INT.withName("otmsXHeight"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("left"),
            JAVA_INT.withName("top"),
            JAVA_INT.withName("right"),
            JAVA_INT.withName("bottom")
        ).withName("otmrcFontBox"),
        JAVA_INT.withName("otmMacAscent"),
        JAVA_INT.withName("otmMacDescent"),
        JAVA_INT.withName("otmMacLineGap"),
        JAVA_INT.withName("otmusMinimumPPEM"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("otmptSubscriptSize"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("otmptSubscriptOffset"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("otmptSuperscriptSize"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y")
        ).withName("otmptSuperscriptOffset"),
        JAVA_INT.withName("otmsStrikeoutSize"),
        JAVA_INT.withName("otmsStrikeoutPosition"),
        JAVA_INT.withName("otmsUnderscoreSize"),
        JAVA_INT.withName("otmsUnderscorePosition"),
        RuntimeHelper.POINTER.withName("otmpFamilyName"),
        RuntimeHelper.POINTER.withName("otmpFaceName"),
        RuntimeHelper.POINTER.withName("otmpStyleName"),
        RuntimeHelper.POINTER.withName("otmpFullName")
    ).withName("_OUTLINETEXTMETRICW");
    static final VarHandle const$4 = constants$975.const$3.varHandle(MemoryLayout.PathElement.groupElement("otmSize"));
    static final VarHandle const$5 = constants$975.const$3.varHandle(MemoryLayout.PathElement.groupElement("otmFiller"));
}


