// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$727 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$727() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "EqualPrefixSid",
        constants$34.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "EqualSid",
        constants$34.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "FindFirstFreeAce",
        constants$34.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "FreeSid",
        constants$33.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "GetAce",
        constants$485.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "GetAclInformation",
        constants$584.const$5
    );
}


