// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$564 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$564() {}
    static final VarHandle const$0 = constants$562.const$5.varHandle(MemoryLayout.PathElement.groupElement("lpThreadLocalBase"));
    static final VarHandle const$1 = constants$562.const$5.varHandle(MemoryLayout.PathElement.groupElement("lpStartAddress"));
    static final VarHandle const$2 = constants$562.const$5.varHandle(MemoryLayout.PathElement.groupElement("lpImageName"));
    static final VarHandle const$3 = constants$562.const$5.varHandle(MemoryLayout.PathElement.groupElement("fUnicode"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("dwExitCode")
    ).withName("_EXIT_THREAD_DEBUG_INFO");
    static final VarHandle const$5 = constants$564.const$4.varHandle(MemoryLayout.PathElement.groupElement("dwExitCode"));
}


