// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1985 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1985() {}
    static final VarHandle const$0 = constants$1984.const$0.varHandle(MemoryLayout.PathElement.groupElement("cbWrappingKey"));
    static final VarHandle const$1 = constants$1984.const$0.varHandle(MemoryLayout.PathElement.groupElement("cbIsolatedKey"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("Version"),
            JAVA_INT.withName("KeyUsage"),
            MemoryLayout.paddingLayout(4),
            JAVA_INT.withName("cbAlgName"),
            JAVA_INT.withName("cbNonce"),
            JAVA_INT.withName("cbAuthTag"),
            JAVA_INT.withName("cbWrappingKey"),
            JAVA_INT.withName("cbIsolatedKey")
        ).withName("Header")
    ).withName("_NCRYPT_EXPORTED_ISOLATED_KEY_ENVELOPE");
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("Magic"),
        JAVA_INT.withName("Version"),
        JAVA_INT.withName("HeaderSize"),
        JAVA_INT.withName("cbCertifyInfo"),
        JAVA_INT.withName("cbSignature"),
        JAVA_INT.withName("cbTpmPublic")
    ).withName("__NCRYPT_PCP_TPM_WEB_AUTHN_ATTESTATION_STATEMENT");
    static final VarHandle const$4 = constants$1985.const$3.varHandle(MemoryLayout.PathElement.groupElement("Magic"));
    static final VarHandle const$5 = constants$1985.const$3.varHandle(MemoryLayout.PathElement.groupElement("Version"));
}


