// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _DEVICE_DSM_CONVERSION_OUTPUT DEVICE_DSM_CONVERSION_OUTPUT;
 * }
 */
public final class DEVICE_DSM_CONVERSION_OUTPUT extends _DEVICE_DSM_CONVERSION_OUTPUT {

    // Suppresses default constructor, ensuring non-instantiability.
    private DEVICE_DSM_CONVERSION_OUTPUT() {}
}


