// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct tagEMRANGLEARC EMRANGLEARC;
 * }
 */
public final class EMRANGLEARC extends tagEMRANGLEARC {

    // Suppresses default constructor, ensuring non-instantiability.
    private EMRANGLEARC() {}
}


