// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _HMAC_Info HMAC_INFO;
 * }
 */
public final class HMAC_INFO extends _HMAC_Info {

    // Suppresses default constructor, ensuring non-instantiability.
    private HMAC_INFO() {}
}


