// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct tagINPUT_INJECTION_VALUE INPUT_INJECTION_VALUE;
 * }
 */
public final class INPUT_INJECTION_VALUE extends tagINPUT_INJECTION_VALUE {

    // Suppresses default constructor, ensuring non-instantiability.
    private INPUT_INJECTION_VALUE() {}
}


