// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*LPDRVCALLBACK)(struct HDRVR__*,unsigned int,unsigned long long,unsigned long long,unsigned long long);
 * }
 */
public interface LPDRVCALLBACK {

    void apply(java.lang.foreign.MemorySegment _x0, int _x1, long _x2, long _x3, long _x4);
    static MemorySegment allocate(LPDRVCALLBACK fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$1553.const$5, fi, constants$1553.const$2, scope);
    }
    static LPDRVCALLBACK ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, int __x1, long __x2, long __x3, long __x4) -> {
            try {
                constants$1553.const$4.invokeExact(symbol, __x0, __x1, __x2, __x3, __x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


