// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _OUTPUT_DEBUG_STRING_INFO OUTPUT_DEBUG_STRING_INFO;
 * }
 */
public final class OUTPUT_DEBUG_STRING_INFO extends _OUTPUT_DEBUG_STRING_INFO {

    // Suppresses default constructor, ensuring non-instantiability.
    private OUTPUT_DEBUG_STRING_INFO() {}
}


