// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * unsigned int (*PGET_SYSTEM_WOW64_DIRECTORY_W)(unsigned short* lpBuffer,unsigned int uSize);
 * }
 */
public interface PGET_SYSTEM_WOW64_DIRECTORY_W {

    int apply(java.lang.foreign.MemorySegment lpBuffer, int uSize);
    static MemorySegment allocate(PGET_SYSTEM_WOW64_DIRECTORY_W fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$800.const$5, fi, constants$65.const$2, scope);
    }
    static PGET_SYSTEM_WOW64_DIRECTORY_W ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _lpBuffer, int _uSize) -> {
            try {
                return (int)constants$800.const$4.invokeExact(symbol, _lpBuffer, _uSize);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


