// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*PUMS_SCHEDULER_ENTRY_POINT)(enum _RTL_UMS_SCHEDULER_REASON,unsigned long long,void*);
 * }
 */
public interface PUMS_SCHEDULER_ENTRY_POINT {

    void apply(int _x0, long _x1, java.lang.foreign.MemorySegment _x2);
    static MemorySegment allocate(PUMS_SCHEDULER_ENTRY_POINT fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$763.const$0, fi, constants$482.const$2, scope);
    }
    static PUMS_SCHEDULER_ENTRY_POINT ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int __x0, long __x1, java.lang.foreign.MemorySegment __x2) -> {
            try {
                constants$482.const$4.invokeExact(symbol, __x0, __x1, __x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


