// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _SCHANNEL_ALG SCHANNEL_ALG;
 * }
 */
public final class SCHANNEL_ALG extends _SCHANNEL_ALG {

    // Suppresses default constructor, ensuring non-instantiability.
    private SCHANNEL_ALG() {}
}


