// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _SCM_BUS_PROPERTY_SET SCM_BUS_PROPERTY_SET;
 * }
 */
public final class SCM_BUS_PROPERTY_SET extends _SCM_BUS_PROPERTY_SET {

    // Suppresses default constructor, ensuring non-instantiability.
    private SCM_BUS_PROPERTY_SET() {}
}


