// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _STORAGE_DEVICE_ATTRIBUTES_DESCRIPTOR {
 *     DWORD Version;
 *     DWORD Size;
 *     DWORD64 Attributes;
 * } STORAGE_DEVICE_ATTRIBUTES_DESCRIPTOR
 * }
 */
public class STORAGE_DEVICE_ATTRIBUTES_DESCRIPTOR extends _STORAGE_DEVICE_ATTRIBUTES_DESCRIPTOR {

    STORAGE_DEVICE_ATTRIBUTES_DESCRIPTOR() {
        // Should not be called directly
    }
}

