// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct tagSTATPROPSTG {
 *     LPOLESTR lpwstrName;
 *     PROPID propid;
 *     VARTYPE vt;
 * };
 * }
 */
public class tagSTATPROPSTG {

    public static MemoryLayout $LAYOUT() {
        return constants$3604.const$0;
    }
    public static VarHandle lpwstrName$VH() {
        return constants$3604.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * LPOLESTR lpwstrName;
     * }
     */
    public static MemorySegment lpwstrName$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$3604.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * LPOLESTR lpwstrName;
     * }
     */
    public static void lpwstrName$set(MemorySegment seg, MemorySegment x) {
        constants$3604.const$1.set(seg, x);
    }
    public static MemorySegment lpwstrName$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$3604.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void lpwstrName$set(MemorySegment seg, long index, MemorySegment x) {
        constants$3604.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle propid$VH() {
        return constants$3604.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * PROPID propid;
     * }
     */
    public static int propid$get(MemorySegment seg) {
        return (int)constants$3604.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * PROPID propid;
     * }
     */
    public static void propid$set(MemorySegment seg, int x) {
        constants$3604.const$2.set(seg, x);
    }
    public static int propid$get(MemorySegment seg, long index) {
        return (int)constants$3604.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void propid$set(MemorySegment seg, long index, int x) {
        constants$3604.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle vt$VH() {
        return constants$3604.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * VARTYPE vt;
     * }
     */
    public static short vt$get(MemorySegment seg) {
        return (short)constants$3604.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * VARTYPE vt;
     * }
     */
    public static void vt$set(MemorySegment seg, short x) {
        constants$3604.const$3.set(seg, x);
    }
    public static short vt$get(MemorySegment seg, long index) {
        return (short)constants$3604.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void vt$set(MemorySegment seg, long index, short x) {
        constants$3604.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


