// Generated by jextract

package com.twitter.teruteru128.preview.windows;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _TXFS_MODIFY_RM TXFS_MODIFY_RM;
 * }
 */
public final class TXFS_MODIFY_RM extends _TXFS_MODIFY_RM {

    // Suppresses default constructor, ensuring non-instantiability.
    private TXFS_MODIFY_RM() {}
}


