# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        cache: 'gradle'
        distribution: 'temurin'
        java-version: |
          21
          22
    - uses: gradle/actions/wrapper-validation@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        add-job-summary-as-pr-comment: on-failure
    - name: Build with Gradle
      run: ./gradlew -Dorg.gradle.java.home=${JAVA_HOME_21_X64} build
